Enlaces links incrustados
BlancaCC/TFG-Estudio-de-las-redes-neuronales pull request #102
Opened 2022-05-23 21:19 UTC by BlancaCC

Los enlaces ya no son citas, sino links incrustados. 
Con esto close #97

2022-05-24 15:10 UTC, JJ commented on .github/workflows/neural-networks-library.yaml
> +              version: '1'
No estás usando la versión que has definido previamente en `matrix`. Si realmente vas a probar sólo una versión, yo directamente quitaría el matrix.

2022-05-24 15:11 UTC, JJ commented on .github/workflows/neural-networks-library.yaml
> +      - biblioteca-redes-neuronales
No pongas las ramas de forma arbitraria. Entiende qué es lo que hace cada uno de estos *triggers* y modifícalos en consecuencia.

2022-05-24 15:12 UTC, JJ commented on .github/workflows/neural-networks-library.yaml
> +    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
No tengo muy claro tampoco por qué haces esto. No vas a usar matrix, realmente, ni testear para diferentes sistemas operativos. Si adoptáis una plantilla de algún lado, tratad de entender qué hace y si se aplica a tu caso determinado.

2022-05-24 15:13 UTC, JJ commented on .github/workflows/neural-networks-library.yaml
> +    runs-on: ${{ matrix.os }}
Tienes un solo sistema operativo definido. Ponlo aquí directamente.
Tampoco es que entienda qué tiene que ver esto con el tema del PR, pero bueno...

2022-05-24 15:15 UTC, JJ commented on Biblioteca-Redes-Neuronales/src/activation_functions.jl
> +module ActivationFunctions
Si es que tienes esto en otra rama, puedes hacer dos cosas
* Hacer PR a la rama en la que está, en vez de a la principal.
* Si no se necesita esto para que la otra rama pase, simplemente hazlo desde main. Luego se fusiona y listo.

2022-05-24 15:33 UTC, BlancaCC commented
@JJ, me acabo de dar cuenta que saqué la rama del PR #96 por eso tiene tantísimos commits  y ficheros los únicos nuevos son los dos últimos commits

2022-05-24 15:35 UTC, JJ commented
> @JJ, me acabo de dar cuenta que saqué la rama del PR #96 por eso tiene tantísimos commits y ficheros los únicos nuevos son los dos últimos commits

Simplemente haz un rebase a esa rama. Lo puedes hacer directamente desde la web, seleccionando esa rama en vez de `main`

2022-05-24 15:39 UTC, JJ commented
Pero no pierdas los comentarios que he hecho aquí, porfa...

2022-05-24 15:42 UTC, JJ requested changes
Algunos detalles, principalmente el cambio es que sustituyas el enlace a la hoja de cálculo con una tabla y/o gráfico.

2022-05-24 15:42 UTC, JJ commented on .github/workflows/personal-dictionary.txt
> +sigmodea
Ten cuidado de no introducir errores en el diccionario, porfa.

2022-05-24 15:42 UTC, JJ commented on Memoria/capitulos/0-Metodologia/introduccion.tex
> +Puede encontrar su declaración en las historias de usuario definidas en \href{https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales}{nuestro repositorio
Pon un enlace directamente a estas, con la etiqueta correspondiente.

2022-05-24 15:42 UTC, JJ commented on Memoria/capitulos/0-Metodologia/introduccion.tex
> +en las siguiente \href{https://docs.google.com/spreadsheets/d/1TCcKQIKjKW9sMSU2f6obN9gHgv3c8UEdjmONkBlv42M/edit?usp=sharing}{hoja de cálculo}.
Es mejor que pongas una tabla aquí.

2022-05-24 15:46 UTC, JJ commented on Memoria/capitulos/0-Metodologia/introduccion.tex
> +en las siguiente \href{https://docs.google.com/spreadsheets/d/1TCcKQIKjKW9sMSU2f6obN9gHgv3c8UEdjmONkBlv42M/edit?usp=sharing}{hoja de cálculo}.
Ponlo entonces en un comentario, y no en el texto. O pon una marca de "Issue #46 aquí"

2022-05-24 15:49 UTC, BlancaCC commented on Memoria/capitulos/0-Metodologia/introduccion.tex
> +en las siguiente \href{https://docs.google.com/spreadsheets/d/1TCcKQIKjKW9sMSU2f6obN9gHgv3c8UEdjmONkBlv42M/edit?usp=sharing}{hoja de cálculo}.
¿Con comentario o marca te refieres a que ponga literalmente en el texto eso? ¿O hay alguna funcionalidad de GitHub que se me escapa?

2022-05-25 15:30 UTC, merged

2022-05-25 16:15 UTC, JJ commented on Memoria/capitulos/0-Metodologia/introduccion.tex
> +en las siguiente \href{https://docs.google.com/spreadsheets/d/1TCcKQIKjKW9sMSU2f6obN9gHgv3c8UEdjmONkBlv42M/edit?usp=sharing}{hoja de cálculo}.
Si, o algo por el estilo.

2022-05-25 16:15 UTC, JJ commented on Memoria/capitulos/5-Estudio_experimental/funciones_activacion.tex
>      \item Para el \textit{grupo escalera}: No se ha rechazado la hipótesis nula, luego a priori no hay deferencia significativa y podemos seleccionar el candidato que queramos.
typo: deferencia.