Se pulen las matemáticas
BlancaCC/TFG-Estudio-de-las-redes-neuronales pull request #106
Opened 2022-05-24 21:36 UTC by BlancaCC

Revisión de modificaciones y ampliaciones matemáticas. 

Agradecería si se pudiera revisar algunas secciones matemáticas 
que han sido añadidas o modificadas estos últimos días, las más importantes son: 

-  **Capítulo de teoría de la aproximación** que comprende las páginas de la 31 a la 38. 
Este capítulo no ha sido corregido nunca, en él no solo se demuestran los teoremas más importantes que se utilizan en la demostración de la convergencia de las redes neuronales; sino que me he tomado la libertad de utilizarlo para introducir de manera intuitiva porqué se necesitan las funciones de activación.Si no os gusta lo quito. 

-  **Consideraciones sobre la capacidad de cálculo** Se ha añadido un resultado que ve que las redes neuronales en los racionales son densas en los reales. 
Comprende las páginas 68, 69. 

- **Capítulo 6: Caracterización de las funcioens de activación**
pag 93 - 99

Por supuesto si de refilón se ve algún otro error por mi parte encantada de cambiarlo. 
El criterio de aceptación de este PR es que @JJ y @JavierMeri den su visto bueno.

El pdf recién compilado es : 
[tfg-24-05-2022.pdf](https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/files/8766369/tfg-24-05-2022.pdf)
 
Este PR closes #103 y corrige algún comentario de JJ en los que respecta al capítulo 6 de #96

2022-05-25 17:42 UTC, JJ requested changes
Algunos errores que veo, no sé si son de este o anteriores
* Nunca se pone . después de ?
* Algunas ecuaciones están numeradas, otras no. Supongo que principalmente numeras las que vas a citar luego, pero no sé si es así. 
* Recuerda poner siempre introducciones a capítulos y secciones (si tienen subsecciones). Por ejemplo, el 4 no la tiene. Estas introducciones tienen que enlazar con los capítulos anteriores y explicar la estructura de la argumentación a continuación.
* Aproximar "la image" → corregir
* Los cuadros de "aportación original" deberían de tener un espacio en blanco alrededor; se pegan demasiado a las líneas anteriores y siguiente. Por otro lado, muy claritos. 
* Estas aportaciones originales deberías relacionarlas con los objetivos del trabajo; sea a continuación, en las conclusiones de cada capítulo, o en algún lugar. Por ejemplo, que se puedan combinar diferentes funciones de activación no tengo claro que contribuya a optimizar la red neuronal; más bien al contrario, porque al aumentar el espacio de búsqueda de funciones de activación hace el diseño más complejo. Ahora, si eso redunda en una mayor velocidad para encontrar la solución, el *trade-off* puede merecer la pena. Evidentemente, si como dices eso contribuye a restringir el espacio al no tener que investigar diferentes números de neuronas será positivo, pero como en la pistola de Chejov, si sacas una hipótesis tienes que usarla. 
* En la explicación del lema 4.7 no veo que hagas ninguna mención a la función de activación, que es de lo que trata el lema. 
* Cuando tratas con funciones de activación que usen racionales, puedes hacer mención al hecho del múltiple dispatch del que he hablado en #96. De hecho, Julia tiene [números racionales](https://docs.julialang.org/en/v1/manual/complex-and-rational-numbers/#Rational-Numbers) Aunque esta parte sea matemática, puede poner notas del tipo "Ojalá hubiera un lenguaje de programación que pudiera tratar con estos tipos explícitamente)
* ahora que lo pienso, "Aportación original" no tiene mucho contraste en el título. Siguiendo la accesibilidad universal de la que ya hemos hablado, por favor trata de que resalte más el título
* En Algoritmo1 pone distanciaMnima
* mismo "años"
* Yo no pondría tan explícitamente parte 1 y 2, porque pueden desconectar los matemáticos (y viceversa). Si lo ves estrictamente necesario sí, pero yo trataría de no hacer una división tan clara para que todo sea legible (y llamativo) para todos/as. En ese sentido, en 5 podrías introducir algo sobre el diseño de las clases correspondientes, igual que en 6
* 
![Captura de pantalla de 2022-05-25 19-35-01](https://user-images.githubusercontent.com/500/170327815-cdeb3f21-cc7e-483b-bbbf-e9d6420c2522.png)
Mujer, hasta ahí llegamos. Ya sabemos que no es no.
* Explica como concepto "actual" que se puede consultar el capítulo 4, creo que era, sobre la posibilidad de que se usen funciones polinómicas y de otro tipo. 
* Justifica las que añades a "nuestra colección". 
* Usa siempre la misma terminología. A la función rampa la llamas rampa(x), a la umbral threshold(x).
* El teorema 6.1 tienes que justificar qué aporta a los objetivos. A priori, yo diría que ahorra una multiplicación, pero no lo tengo muy claro.
* En la tabla, expresa media y sigma de la forma habitual, con ±
* Deberías hacer también un boxplot + whiskers y eso

OK, yo creo que ya tienes para un rato. Imagino que @JavierMeri tendrá bastante más que decir.

2022-05-26 09:10 UTC, JavierMeri commented
@BlancaCC te paso el .pdf con las correcciones. He revisado todas las partes que pedías y las primeras 20 páginas.
El problema fundamental que encuentro es que no se entiende la demostración del Teorema de Banach-Stone, ahí tienes trabajo.
[tfg-24-05-2022Corregido.pdf](https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/files/8777726/tfg-24-05-2022Corregido.pdf)

2022-05-31 08:42 UTC, JJ requested changes
Principalmente hay que revisarlo por los muchos TODOs. Si se han dejado para más tarde, se pueden poner como comentarios. El resto son principalmente correcciones. Buen trabajo, en todo caso

2022-05-31 08:42 UTC, JJ commented on Memoria/capitulos/0-Metodologia/Comentarios_previos.tex
> +    aclarar conceptos matemáticos o informáticos y ofertar la idea intuitiva que
"ofrecer"

2022-06-01 06:42 UTC, BlancaCC commented on Memoria/capitulos/3-Teoria_aproximacion/4_Conclusiones.tex
> +De todas formas no abandonemos del todo esta teoría, porque como ya veremos el
Teoría, porque se refiere a teoría de aproximación

2022-06-01 07:02 UTC, BlancaCC commented
@JJ Te respondo al comentario con todas las propuestas de cambio: 
> Nunca se pone . después de ?
> 
1. No he encontrado dónde he puesto ?. Supongo que se verá en el pdf, cuando haga una lectura global quizás me de cuenta...

> Algunas ecuaciones están numeradas, otras no. 
>  Supongo que principalmente numeras las que vas a 
> citar luego, pero no sé si es así.

 [No creo que sea buena idea porque distrae al lector de lo esencial](https://tex.stackexchange.com/questions/29267/which-equations-should-be-numbered) 
[x]
> Los cuadros de "aportación original" deberían de 
> tener un espacio en blanco alrededor; se pegan 
> demasiado a las líneas anteriores y siguiente. Por
>  otro lado, muy claritos.
Le he añadido hueco por abajo y por arriba, pero lo de *muy clarito* no lo entiendo. Mi intención era que tampo destacase mucho el fundo, de ahí el gris.

2022-06-01 08:27 UTC, BlancaCC commented on Memoria/capitulos/4-Actualizacion_redes_neuronales/construccion-evaluacion-red-neuronal.tex
> +    Esta idea abre la puerta a determinar mediante algoritmos
@JJ He leído los artículos y aún así nuestro enfoque sería distinto, voy añadir un capítulo 8 comentándolo.
El artículo que más se parece es el segundo, te comento las ventajas que tenemos frente a él: 
- **Nuestro espacio de búsqueda es considerablemente menor.**  (Esto es una ventaja muy grande que ofrece el trabajar solo con una capa oculta)
Nótese que están utilizando DNN, por lo tanto cuando calculan las posibilidades, el espacio de búsqueda sería:

número neuronas ^ (número funciones activación)

<img width="624" alt="Captura de Pantalla 2022-06-01 a las 10 09 30" src="https://user-images.githubusercontent.com/32298296/171358482-4ca57daf-c614-499f-bda7-152b5bcfa6d3.png">
al trabajar con una sola capa oculta las neuronas son conmutativas, es decir da igual que pongamos una función de activación en una neurona que en otra, siempre que el número se mantenga invariante  (esta idea se me ha ocurrido gracias al artículo, no va a ser nada difícil de demostrar... vaya buen teorema que me has dado idea de incluir en la memoria 😜)
en nuestro caso sería

número neuronas * (número funciones activación)

¡Hemos pasado de una relación exponencial a una lineal!

- Contamos con el algoritmo de inicialización de pesos para ahorrarnos el entrenamiento de la red.

2022-06-01 09:09 UTC, BlancaCC commented
@JavierMeri agradecería si revisaras las demostraciones que me comentaste que reescribiera: 

1. **Teorema de Stone Weierstrass** en el manual que estaba siguiendo no estaba, así que he escrito una demostración de mi cosecha, por lo que seguramente exista otra más simple pero bueno. 
Los cambios se reflejan en las páginas: 32-36 (se ha quedado bien largo 🤣).

2. **Teorema de relación funciones de activación con aplicaciones afines** Lo he afinado mucho más. De hecho lo he separado primero en el teorema 6.1 y luego en el corolario 6.1


[tfg-01-06-2022.pdf](https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/files/8812734/tfg-01-06-2022.pdf)

2022-06-01 10:47 UTC, JJ commented
@BlancaCC claritos de bien

2022-06-02 10:09 UTC, JavierMeri commented
@BlancaCC adjunto el .pdf con las correcciones. El Teorema de Banach Stone está muy bien (no desesperes con los pequeños cambios que he puesto). El Teorema 6.1 y el Corolario 6.1 han quedado fenomenal. El único detalle es que creo que para hacer la demostración del Teorema 6.1 es necesario suponer que \phi es invertible.  

[tfg-01-06-2022Corregido.pdf](https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/files/8822738/tfg-01-06-2022Corregido.pdf)

2022-06-02 10:19 UTC, BlancaCC commented
@JavierMeri Gracias por las correciones Javier, las he ojeado y agradezco que me enseñes a escribir bien matemáticas 😊. 

Respecto a lo de invertible no lo he puesto porque es implícito a las restricciones de los coeficientes, al dar su expresión matricial y esta no ser nula y de determinante distinto de cero es invertible. 
La expresión no es nula ya que los elementos de la diagonal de la matriz pertenecena  R^\times  (unidades de R, es decir, todos menos el 0. (Que viendo tus correcciones  ahí me ha salido la vena algebrista, debería de haber puesto R* y se hubiera entendido mejor)) 

El resto de cambios tienes toda la razón , lo dicho, muchas gracias

2022-06-02 14:48 UTC, merged