Descripción del experimento #109
BlancaCC/TFG-Estudio-de-las-redes-neuronales pull request #110
Opened 2022-05-25 18:15 UTC by BlancaCC

Escribo un borrador de #109 para que vayamos refinándolo 
Cuando @JJ  de el visto nuevo close #109

Por lo pronto el experimento trata de estudiar el algoritmo de inicialización de pesos de redes neuronales
Incluye:
- Descripción del experimento
- Descripción del test de hipótesis
- Requisitos técnicos (vamos lo que hay que programar)

2022-05-25 18:19 UTC, BlancaCC commented on Memoria/capitulos/5-Estudio_experimental/2_algoritmo-inicializacion-pesos.tex
> +Para ello se realizará un test de Wilcoxon, con las siguientes hipótesis
He escrito Wilcoxon porque creo que nos permitiría sacar resultados con menos muestras y sin asumir la distribución normal de los tiempo. 
¿se suelen plantear otros tipos de test?
Por ejemplo hacer que el número de muestra sea mayor que 30 y hacer una prueba t-Student

2022-05-25 18:21 UTC, BlancaCC commented on Memoria/capitulos/5-Estudio_experimental/2_algoritmo-inicializacion-pesos.tex
> +
@JJ He pensado en implementar la red neuronal como un tipo de dato. 
Y que el resto sean funciones que trabajan con esos tipos ¿Cómo lo ves? (Me tengo que poner con lo que me has explicado de estructura de datos)

2022-05-25 18:21 UTC, BlancaCC commented on Memoria/capitulos/5-Estudio_experimental/2_algoritmo-inicializacion-pesos.tex
> +    \item \href{https://github.com/JuliaStats/RDatasets.jl}{Julia contiene las base de datos estándar de R}.
Comenzaremos probando con bases de datos de juguete 
 y en función de tiempo y prestaciones ya veremos si merece la pena plantearse el uso de datos reales

2022-05-25 18:26 UTC, BlancaCC commented on Memoria/capitulos/5-Estudio_experimental/2_algoritmo-inicializacion-pesos.tex
> +Por simplicidad fijaremos una función de activación
Para que fuera riguroso y exhaustivo debería de realizarse el experimento con combinaciones de todos estos parámetros. 
Esto puede ser un poco locura así que se podría fijar además: 
- la entrada $d$ y $s$: a la entrada y salida a los databas que tengamos a mano (que pueden ser tres por ejemplo)
- La función de activación probar dos, por ejemplo una ReLU (por ser ampliamente utilizada) y la otra ni idea

2022-05-25 18:30 UTC, BlancaCC commented on Memoria/capitulos/5-Estudio_experimental/2_algoritmo-inicializacion-pesos.tex
> +    \item A mismo tiempo es más ventajoso que utilizar un descenso de gradiente.
No tengo muy claro si me va a dar tiempo a esta segunda experimentación. Voy a centrarme en la primera  y dejarla bien hecha. 
¿Crees @JJ que merecería la pena enfocar entonces el experimento/comparativa a realizar de otra manera?

2022-05-31 08:48 UTC, JJ commented on Memoria/capitulos/5-Estudio_experimental/2_algoritmo-inicializacion-pesos.tex
> +Para ello se realizará un test de Wilcoxon, con las siguientes hipótesis
Wilcoxon dos a dos está bien para empezar. Por favor, documenta siempre las elecciones

2022-05-31 08:48 UTC, JJ commented on Memoria/capitulos/5-Estudio_experimental/2_algoritmo-inicializacion-pesos.tex
> +
Correcto.

2022-05-31 08:49 UTC, JJ commented on Memoria/capitulos/5-Estudio_experimental/2_algoritmo-inicializacion-pesos.tex
> +Por simplicidad fijaremos una función de activación
Tienes que hacer un pequeño diseño experimental, pero yo diría que para un TFG basta con que uses "reglas del pulgar" para probar cosas. Recuerda, no es una tesis.

2022-05-31 08:54 UTC, JJ reviewed
Sólo unos comentarios, porque entiendo que está en borrador todavía.

2022-05-31 08:54 UTC, JJ commented on Memoria/capitulos/5-Estudio_experimental/2_algoritmo-inicializacion-pesos.tex
> +en \ref{section:inicializar_pesos} que plantea dos objetivos múltiples en lo que respecta a la inicialización de pesos de una red neuronal:
quita "múltiples"

2022-05-31 08:54 UTC, JJ commented on Memoria/capitulos/5-Estudio_experimental/2_algoritmo-inicializacion-pesos.tex
> +    \item A mismo tiempo es más ventajoso que utilizar un descenso de gradiente.
¿Usar un descenso de gradiente para *inicializar*? ¿Es eso lo que quieres decir?

2022-05-31 08:54 UTC, JJ commented on Memoria/capitulos/5-Estudio_experimental/2_algoritmo-inicializacion-pesos.tex
> +Para ello se han diseñado dos experimentos:
Explica *ello*. Di qué quieres probar y cómo contribuye a los objetivos.

2022-06-06 17:07 UTC, JJ requested changes
Principal problema es la frase sin terminar. Los tests podrían ser más completos.

2022-06-06 17:07 UTC, JJ commented on Biblioteca-Redes-Neuronales/test/one_layer_neural_network.test.jl
> +    @test length(ForwardPropagation(OLNN,ReLU, [0,1.0])) == output_dimension
Los tests podrían ser un poco más completos. No estás comprobando comportamiento, ni siquiera que corresponda a lo que has probado en matemátias. Idealmente deberías hacerlo.

2022-06-06 17:07 UTC, JJ commented on Memoria/capitulos/5-Estudio_experimental/3_algoritmo-inicializacion-pesos.tex
> +    datos de test.} Se utilizarán para el cálculo del error.
Idealmente tests del algoritmo == tests del código. Si no tienes tiempo de hacerlo, sería  conveniente que hicieras lo más posible, por ejemplo que los pesos  cumplen el criterio dado tras la inicialización.

2022-06-06 17:07 UTC, JJ commented on Memoria/capitulos/5-Estudio_experimental/3_algoritmo-inicializacion-pesos.tex
> +Deberá de implementarse del algoritmo  \ref{algo:algoritmo-iniciar-pesos} con todos los requisitos y atributos que ahí se describe.
"Deberá" == obligación
"Deberá de" == posibilidad ("Deberán de ser sobre las tres y media")

2022-06-06 17:07 UTC, JJ commented on Memoria/capitulos/5-Estudio_experimental/3_algoritmo-inicializacion-pesos.tex
> +Por lo que
???

2022-06-20 06:44 UTC, closed without merging