Implementación inicialización de pesos
BlancaCC/TFG-Estudio-de-las-redes-neuronales pull request #116
Opened 2022-06-03 08:49 UTC by BlancaCC

Con el fin de closes #115 necesito implementar el experimento 1
Creo esta rama en borrador para ir mostrando el avance del proceso

2022-06-03 08:49 UTC, BlancaCC commented on Biblioteca-Redes-Neuronales/src/initial_neuronal_network.jl
> +    return S,A,B
Debería de llamar al constructor de una red neuronal con estos parámetros

2022-06-03 08:50 UTC, BlancaCC commented on Biblioteca-Redes-Neuronales/src/one_layer_neuronal_network.jl
>  abstract type AbstractOneLayerNeuralNetwork end
Aquí me gustaría implementar una interfaz, por ahora no sé cómo hacerlo

2022-06-03 08:52 UTC, BlancaCC commented on Biblioteca-Redes-Neuronales/src/one_layer_neuronal_network.jl
> +    W1  # pesos de la entrada a la capa oculta
Las dimensiones quizás son superfluas, redundantes y no optimizan habrá que revisarlo

2022-06-03 08:56 UTC, BlancaCC reviewed
Aquí en general está la estructura de lo que quiero hacer: 
Falta construir todos los test

2022-06-03 08:56 UTC, BlancaCC commented on Biblioteca-Redes-Neuronales/src/one_layer_neuronal_network.jl
> +            Los tamaños encontrados son:
Faltan añadir más comprobaciones de longitud

2022-06-03 08:56 UTC, BlancaCC commented on Biblioteca-Redes-Neuronales/test/one_layer_neural_network.test.jl
> +end
Falta comprobar que los tamaños de salida que devuelve el constructor son los correctos

2022-06-03 08:56 UTC, BlancaCC commented on Memoria/capitulos/5-Estudio_experimental/3_algoritmo-inicializacion-pesos.tex
> +
Esto son notas sueltas que he ido tomando y habrá que redactar mejor

2022-06-06 17:20 UTC, JJ reviewed
¿Me ha parecido entender que esto no lo ibas a hacer?

2022-06-08 18:11 UTC, JJ requested changes
Está bien que hagas tests, y es menos que nada, pero los tests tienen que tratar de comprobar que realmente se están comportando las funciones como dice la teoría, hasta el punto que sea posible.

2022-06-08 18:11 UTC, JJ commented on Biblioteca-Redes-Neuronales/src/metric_estimation.jl
> +    diferences = map(norm,eachrow(Y .- f_x))
Estas dos líneas son la función anterior. DRY (don't repeat yourself)

2022-06-08 18:11 UTC, JJ commented on Biblioteca-Redes-Neuronales/src/one_layer_neuronal_network.jl
> +module OneLayerNeuralNetwork
En general, la modularización del código, su organización, las estructuras de datos elegidas y demás deben ser objeto de un desarrollo específico siguiendo una metodología en la que se plantee el problema y se resuelva mediante código. En este caso, se refiere a #115, que no plantea un problema, sino una tarea. #109 sí sería un problema, pero #115 debería haber planteado problemas específicos como qué tipo de funciones exportar, o cómo se relacionan los grupos unos con otros. Incluso reparto en espacios de nombres: muchos ficheros se llaman "one_layer...", podrían estar en un directorio con ese nombre. También se podría decidir si se usan diferentes funciones, o una sola función con un argumento (RandomWeights, fromMatrix). Todo eso se tiene que decidir en función del código que se comparta, por ejemplo.

2022-06-08 18:11 UTC, JJ commented on Biblioteca-Redes-Neuronales/src/one_layer_neuronal_network.jl
>      function OneLayerNeuralNetworkRandomWeights(entry_dimesion,
Las funciones comienzan con minúsculas en Julia https://docs.julialang.org/en/v1/manual/style-guide/

2022-06-08 18:11 UTC, JJ commented on Biblioteca-Redes-Neuronales/src/one_layer_neuronal_network.jl
>      number_of_hide_units :: Int
hidden, no hide

2022-06-08 18:11 UTC, JJ commented on Biblioteca-Redes-Neuronales/src/one_layer_neuronal_network.jl
> +        if !( typeof(S) <: Vector && typeof(A) <: Matrix && typeof(B) <: Matrix )
¿Y por qué no le pones tipo a los argumentos en vez de lanzar un error?

2022-06-08 18:11 UTC, JJ commented on Biblioteca-Redes-Neuronales/src/one_layer_neuronal_network.jl
> +function ForwardPropagation(h,activation_function, x)
Uf, ¿por qué le has quitado el tipo?

2022-06-08 18:11 UTC, JJ commented on Biblioteca-Redes-Neuronales/test/forward_propagation.test.jl
> +        @test OneLayerNeuralNetwork.ForwardPropagation(h, x->x,v ) == [2*v[1], 3*v[2]]
Sólo estás repitiendo las operaciones. En este tipo de bibliotecas, tienes que comprobar que efectivamente se ha llevado a cabo el comportamiento deseado.

2022-06-08 18:11 UTC, JJ commented on Biblioteca-Redes-Neuronales/test/forward_propagation.test.jl
> +    # Calculamos manualmente cuál debiera de ser el resultado
Realmente no estás testeando nada aquí, sólo que la aritmética funciona.

2022-06-09 14:40 UTC, BlancaCC commented on Biblioteca-Redes-Neuronales/test/forward_propagation.test.jl
> +    # Calculamos manualmente cuál debiera de ser el resultado
Quizás no he explicado bien la idea del test, pero la explico aquí (y debiera de trasladarla a la memoria): 
El objetivo del test es comprobar que efectivamente se está haciendo el forward propagación correctamente. 
Ahora bien, por su forma matricial se puede ver como composiciones de matrices de: 
translación, escalado...

Lo que he probado en cada test es esto: 
para escalado sirve, para translación también...
y finalmente para matrices con todas las entradas algún número (por si daba la casualidad que fallaba en las anteriores por tener un ceros en sitios muy concretos)  funciona

2022-06-09 14:54 UTC, BlancaCC commented on Memoria/capitulos/5-Estudio_experimental/3_algoritmo-inicializacion-pesos.tex
> +
No sé si entiendo muy bien a lo que te refieres JJ, por lo que veo DrWatson está más ligado a tema de gestionar proyectos con experimentos (como es nuestro caso, pero un poco tarde para ponerse ahora con ello)...

A ver, me estás diciendo que use un tareas de Julia https://docs.julialang.org/en/v1/base/parallel/
para cada test ¿y eso sea lo que llame?

(Tiene sentido ya que no hay interdependencia entre los test, pero no sé si te refieres a otro formato más efectivo)

2022-06-10 10:42 UTC, BlancaCC commented on Biblioteca-Redes-Neuronales/src/one_layer_neuronal_network.jl
>      number_of_hide_units :: Int
Gracias :)

2022-06-11 08:24 UTC, JJ commented on Biblioteca-Redes-Neuronales/src/one_layer_neuronal_network.jl
>  abstract type AbstractOneLayerNeuralNetwork end
Por lo que estoy viendo, no hay forma de hacerlo en Julia. Esto es simplemente una declaración de tipo, pero ya está. [Este issue](https://github.com/JuliaLang/julia/issues/6975) lleva abierto 8 años y pide algo así, pero ya está. Pensaba que era más fácil, pero parece que no lo es.
Para simular este tipo de cosas, se suele crear una clase base que tire excepciones si se trata de llamar a la clase base. En todo caso la declaración de este tipo abstracto te puede ayudar para argumentos de rutinas que sólo usen lo que descienda de este tipo abstracto.

2022-06-11 08:24 UTC, JJ commented on Biblioteca-Redes-Neuronales/src/one_layer_neuronal_network.jl
> +    W1  # pesos de la entrada a la capa oculta
?

2022-06-11 08:26 UTC, JJ commented on Biblioteca-Redes-Neuronales/test/forward_propagation.test.jl
> +    # Calculamos manualmente cuál debiera de ser el resultado
Es simplemente aritmética. Tus funciones son de otro nivel, de entrenamiento. Tendrías que comprobar que disminuye el error a lo largo de las diferentes iteraciones.

2022-06-11 11:27 UTC, BlancaCC commented on Biblioteca-Redes-Neuronales/src/one_layer_neuronal_network.jl
> +function ForwardPropagation(h,activation_function, x)
Porque me daba un error por los módulos que no estaban bien hechos. En el PR #117 se corrige reestructurando los módulos y vuelvo a añadir el tipo.
(Tienes razón de que debiera de comentar mejor los errores en issues)

2022-06-11 11:32 UTC, BlancaCC commented on Biblioteca-Redes-Neuronales/test/forward_propagation.test.jl
> +    # Calculamos manualmente cuál debiera de ser el resultado
No termino de entenderlo, ese test sería más para backpropagation, ¿no? en forward propagation solo se puede comprobar que hace bien la aritmética, ¿no?

2022-06-12 10:14 UTC, JJ commented on Biblioteca-Redes-Neuronales/test/forward_propagation.test.jl
> +    # Calculamos manualmente cuál debiera de ser el resultado
La aritmética la va a hacer siempre bien. La combinación forward + backpropagation disminuyendo el error es lo que tendrías que testear.

2022-06-20 06:44 UTC, closed without merging