Rematar memoria
BlancaCC/TFG-Estudio-de-las-redes-neuronales pull request #118
Opened 2022-06-10 10:49 UTC by BlancaCC

He estado incluyendo los comentarios de código que me iba indicando @JJ
y justificando en la memoria el proceso de elaboración.  Esto debería de close #116 y Close #115

La memoria actual es: 
[tfg-10-06-2022.pdf](https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/files/8878144/tfg-10-06-2022.pdf)

Además durante la implementación me he dado cuenta de algunos detallitos teóricos de la memoria que he corregido. 

Faltan por incorporar algunas correcciones de JJ, pero dejo esto por aquí para que se vaya corrigiendo

2022-06-10 15:46 UTC, BlancaCC commented
Al final me he animado a probar los resultados con un conjunto de datos real: 
Mi criterio de selección ha sido: 
- Que sea un problema de regresión.
- Que fuera relativamente pequeño.
Este es el seleccionado: 
https://archive.ics.uci.edu/ml/datasets/Airfoil+Self-Noise#

2022-06-10 20:16 UTC, BlancaCC commented on Experimentos/inicializacion-pesos-red-neuronal/2_air_self_noise.jl
> +(0.1759656798601324, 0.1439178380239382, 0.1418858978301221, 0.1617093840740258)
@JJ  La situación aquí es la siguiente: 
Los datos están normalizados a [0,1]
La tupla de resultados son los siguientes parámetros:
(error medio, mediana del error, desviación típica del error, índice de correlación)

Los resultados con la red neuronal aleatoria son malísimos como era de esperar: 
ya que en un rango de [0,1] el error medio se dispara 404 y además el índice de correlación es negativo (teóricamente debiera de estar entre [0,1], pero cuando es muy malo al computarse podría darse negativo, cosas de informática...)

El de la h con nuestro algoritmo parece mejor, la media  de error es de 0.17 +- 0.141
pero cuando uno mira la correlación ve que no tiene na que ver 
Mis preguntas son: 
¿Estoy mirando los parámetros adecuados?
¿Son estos datos una vergüenza y mejor no los enseño?
(Recordatorio de que este algoritmo pretende inicializar los datos de una red neuronal)

2022-06-11 07:44 UTC, JJ commented on Experimentos/inicializacion-pesos-red-neuronal/2_air_self_noise.jl
> +(0.1759656798601324, 0.1439178380239382, 0.1418858978301221, 0.1617093840740258)
No puedes comparar una red aleatoria con otra que tiene algún algoritmo de inicialización en los resultados iniciales. Tienes que mirar el tiempo que hace falta para entrenar, o los recursos que necesita para alcanzar algún resultado (teniendo en cuenta que una inicialización y otra necesitan recursos diferentes). Evidentemente, un algoritmo de inicialización que necesite el conjunto de entrenamiento va a ser mejor que otro que no, pero no estamos comparando la situación inicial, sino la situación una vez entrenada, sin perder de vista el objetivo, que es que sea más fácil entrenar las redes o más asequible.

2022-06-11 08:15 UTC, JJ requested changes
Los cambios se refieren principalmente a la organización del código. Ánimo que ya queda poco.

2022-06-11 08:15 UTC, JJ commented on Experimentos/inicializacion-pesos-red-neuronal/2_air_self_noise.jl
> +Random.seed!(1)
Si usas siempre la misma semilla, siempre tendrás el mismo resultado. Los tests no deben depender en resultados específicos. NUNCA uses la misma semilla en experimentos en heurísticas. Y no sé por qué os dijeron esto en la asignatura correspondiente, de verdad que no lo entiendo.

2022-06-11 08:15 UTC, JJ commented on Experimentos/inicializacion-pesos-red-neuronal/2_air_self_noise.jl
> +#   EXPERIMENTO SINTÉTICO DE NUESTRO algoritmo
No hay ningún issue que pida este experimento sintético, ni está claro por qué se hace más allá del #117. Todo el código debe avanzar objetivos y dar valor al usuario. En ese sentido, no tengo muy claro por qué hace falta este experimento específico.

2022-06-11 08:15 UTC, JJ commented on Experimentos/inicializacion-pesos-red-neuronal/2_air_self_noise.jl
> +input_dimension = 5
¿Por qué no es esto parte de la configuración?

2022-06-11 08:15 UTC, JJ commented on Experimentos/inicializacion-pesos-red-neuronal/2_air_self_noise.jl
> +n = ceil(Integer, index*0.9) # numbers of nodes
¿Estás usando una heurística para el número de nodos? ¿De dónde sale?

2022-06-11 08:15 UTC, JJ commented on Experimentos/inicializacion-pesos-red-neuronal/2_air_self_noise.jl
> +Ejecución 2
No acaba de ser una buena idea poner los resultados en el propio código. Deberías tener un directorio con los resultados de los experimentos, preferiblemente de forma procesable.

2022-06-11 08:15 UTC, JJ commented on Experimentos/inicializacion-pesos-red-neuronal/utils/dat_to_csv.jl
> +#################################################################
¿Por qué no está esto en un directorio que salga del directorio principal o lo que sea?
La modularización y la organización de un repositorio también debe seguir mejores prácticas y metodología.

2022-06-11 08:15 UTC, JJ commented on Memoria/capitulos/5-Estudio_experimental/2_descripcion_inicializacion-pesos.tex
> +Presentamos por tanto una propuesta para
Estás metiendo muchas cosas en un solo PR, lo hace difícil de evaluar. Con un *scope* como "rematar la memoria" tiene sentido, pero aún así, sería mejor poner por un lado el código y por otro el texto.

2022-06-11 11:06 UTC, BlancaCC commented on Biblioteca-Redes-Neuronales/src/forward-propagation.jl
> +    s = h.W1 * push!(x_aux,1)
push!  modifica el valor de x, luego es necesaria una copia

2022-06-11 11:10 UTC, BlancaCC commented on Experimentos/inicializacion-pesos-red-neuronal/2_air_self_noise.jl
> +input_dimension = 5
Este fichero era sobretodo para tantear el asunto hoy  tenía pensado hacerlo correctamente

2022-06-11 11:13 UTC, BlancaCC commented on Biblioteca-Redes-Neuronales/src/forward-propagation.jl
> +    x_aux = h.W2 * ∑
Me apunto esto, gracias

2022-06-11 11:17 UTC, BlancaCC commented on Biblioteca-Redes-Neuronales/src/weight-initializer-algorithm/main.jl
> +include("multiple-input-single-ouput.jl")
Para que esté totalmente optimizado cada caso. 
El caso más notable es el de R->R que se ahorra incluso la selección de $p$. 
Además las estructuras o el tipo que se esa en cada estructura es distinto.

2022-06-11 11:20 UTC, BlancaCC commented on Experimentos/inicializacion-pesos-red-neuronal/2_air_self_noise.jl
> +Random.seed!(1)
De acuerdo,  hasta el momento tenía entendido que debía de hacerse siempre fijando semilla: 
para que los experimentos fueran repetidles

2022-06-14 15:40 UTC, JJ requested changes
Principalmente errores de nombres y demás, pero también te agradecería que intentaras al menos justificar las decisiones más importantes (como qué experimentos hacer) con un issue que salga una HU adecuada.

2022-06-14 15:40 UTC, JJ commented on Biblioteca-Redes-Neuronales/test/initial_neuron_network.test.jl
> -###################################################
¿Por qué has borrado esto? ¿Lo has cambiado de nombre? Si cambias las cosas de nombre, usa siempre `git mv`

2022-06-14 15:40 UTC, JJ commented on Experimentos/.config.toml
> +DIRECTORIO_IMAGENES = "./Experimentos/inicializacion-pesos-red-neuronal/img/0_1_aleatorio/" #carpeta que contendrá las imágenes
El problema de dónde guardar los experimentos se suele resolver con lo llamado "experiment registry" o "model registry". Los parámetros y resultados de cada experimento tienen que ir al mismo. Te lo mencioné antes, y es un poco tarde para usarlo ahora, pero podías mencionarlo al menos en "trabajo futuro"
Así evitas los nombres puestos "a jopo" y sobre todo tienes una asociación clara entre modelo y configuración que lo ha creado.

2022-06-14 15:40 UTC, JJ commented on Experimentos/.config.toml
> +# Descomentar: Para mostrar en la carpeta de la memoria
Descomentar tampoco es una forma muy adecuada de configurar experimentos. Como te he comentado, necesitarías un gestor de tareas como Make (u otro) que admita parámetros tales como este, que se pasen como argumento a un programa.
Configurar y gestionar experimentos no es un problema trivial y hay herramientas que te ayudan a hacerlo dentro de lo que se llama, en general, MLOps (también te lo he mencionado alguna vez). Supongo que es muy tarde para usarlo, pero una vez más, para la memoria. Puntualmente, piensa en una forma mejor de configurar experimentos que no implique modificar ficheros que están en el repositorio.

2022-06-14 15:40 UTC, JJ commented on Experimentos/.config.toml
> +NUMERO_PARTICIONES = +15  # Veces que se tomarán medidas
En vez de repetir configuraciones en un solo fichero, igual deberías tener diferentes ficheros.

2022-06-14 15:40 UTC, JJ commented on Experimentos/.config.toml
> +[visualizacion-inicializacion-pesos-R-aleatorio]
No has creado ningún issue para resolver el problema de la configuración, y la mayoría del código que has modificado aquí corresponde a issues que hablan de calidad del código, que poco tienen que ver con el hecho de que tienes que configurar los experimentos. Ninguna decisión de código es obvia, y siempre merece la pena plantear claramente cuál es el problema para tomar en consideración diferentes opciones.

2022-06-14 15:40 UTC, JJ commented on Experimentos/comparativas-funciones-activacion/velocidad_funciones_activacion.jl
> +include("../../OptimimizedNeuralNetwork.jl/src/activation_functions.jl")
Typo: "optimimized"
¿Hace falta que el directorio que incluye el fichero lleve también el `.jl`?

2022-06-14 15:40 UTC, JJ commented on Experimentos/inicializacion-pesos-red-neuronal/0_experimento_sintetico.jl
> +include("../../OptimimizedNeuralNetwork.jl/src/OptimizedNeuronalNetwork.jl")
Usa siempre la misma terminología: "Neural" network (neuronal es en castellano)

2022-06-14 15:40 UTC, JJ commented on Experimentos/inicializacion-pesos-red-neuronal/1_experimento_sintetico_heterogeneo.jl
> +using Random
Especialmente en experimentos, es esencial que platees en un issue el objetivo de este experimento concreto, y las diferentes decisiones que has tomado. Estos commits se refieren a #117, que no plantea ningún problema, y este sólo se refiere a la HU #49, que es la presentación ante el tribunal.
Los experimentos deberían aportar soluciones al cliente HU #48 , pero también #51 y deberían tratar de avanzar en esas HUs. En caso contrario, es complicado justificar las decisiones que se han tomado sobre los conjuntos sintéticos, o los diferentes experimentos.

2022-06-14 15:40 UTC, JJ commented on Memoria/capitulos/0-Metodologia/asignaturas.tex
> +Si bien, es casi imposible enumerar de manera
Fuera ,

2022-06-14 15:40 UTC, JJ commented on Memoria/capitulos/0-Metodologia/asignaturas.tex
> +    \item \textbf{Infraestructura virtual}:la metodología y buenas práctica seguidas han
Te lo agradezco, pero creo que aquí se refiere a asignaturas que hayas hecho...

2022-06-14 15:40 UTC, JJ commented on Memoria/capitulos/0-Metodologia/asignaturas.tex
> +    \item Otras asignaturas que han intervenido \textbf{Programación Orientada a Objeto} \textbf{Diseño y Desarrollo de Sistemas Informáticos}
Espero que no haya habido nada de DDSI. Pero mencionarlo no está mal, quizá.

2022-06-14 15:40 UTC, JJ commented on Memoria/capitulos/0-Metodologia/herramientas.tex
>      \item Ofrece \textit{benchmarks}
resultados de benchmarks, no benchmarks.

2022-06-14 15:40 UTC, JJ commented on Memoria/capitulos/Ejemplo-uso-biblioteca.ipynb
> + "cells": [
Si esto lo vas a usar, tienes que justificarlo e incluirlo en la memoria.

2022-06-15 06:42 UTC, BlancaCC commented on Experimentos/comparativas-funciones-activacion/velocidad_funciones_activacion.jl
> +include("../../OptimimizedNeuralNetwork.jl/src/activation_functions.jl")
Según las [guía de estilo de nombre de paquetes](https://pkgdocs.julialang.org/v1/creating-packages/#Package-naming-guidelines) de Julia sí

2022-06-15 08:39 UTC, BlancaCC commented on Memoria/capitulos/Ejemplo-uso-biblioteca.ipynb
> + "cells": [
Diría que ya está justificado en la memoria en la parte de herramientas 1.6.3 
Concretamente lo  tenía más que nada por comodidad mía, porque he añadido ejemplo de uso de la biblioteca en la memoria.
Pero pensándolo bien puede ser interesante mantenerlo como ejemplo para el readme

2022-06-15 17:37 UTC, JJ reviewed
Sólo un par de comentarios. Por favor, avisa cuando esté listo para revisar.

2022-06-15 17:37 UTC, JJ commented on Project.toml
>  authors = ["Blanca <blancacano2.71828@gmail.com>"]
Ah, que has añadido e a tu nombre... Muy bueno.

2022-06-15 17:37 UTC, JJ commented on Memoria/capitulos/Ejemplo-uso-biblioteca.ipynb
> + "cells": [
REcuerda que tienes que justificarlo también en un issue, pero bueno, si está en la memoria me vale. Si lo vas a añadir al README ponlo también en un issue.

2022-06-15 17:51 UTC, JJ commented on OptimizedNeuralNetwork.jl/src/activation_functions.jl
> -module ActivationFunctions
¿Por qué has borrado esto? Esto es lo que está causando el error en #119 
Incluso aunque se corrija, sigue dando otro error:

```
julia --project=. Experimentos/comparativas-funciones-activacion/velocidad_funciones_activacion.jl
ERROR: LoadError: ArgumentError: Package TimerOutputs [a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.

Stacktrace:
 [1] _require(::Base.PkgId) at ./loading.jl:998
 [2] require(::Base.PkgId) at ./loading.jl:927
 [3] require(::Module, ::Symbol) at ./loading.jl:922
 [4] include(::Module, ::String) at ./Base.jl:377
 [5] exec_options(::Base.JLOptions) at ./client.jl:288
 [6] _start() at ./client.jl:484
in expression starting at /home/jmerelo/Asignaturas/TFG/2022/TFG-Estudio-de-las-redes-neuronales/Experimentos/comparativas-funciones-activacion/velocidad_funciones_activacion.jl:15
make: *** [Makefile:36: experimentos] Error 1
```

Sería conveniente que incluyeras `make experimentos` en algún workflow de integración continua. Es esencial que funcione siempre. No sé cuanto durará, pero incluso aunque dure bastante puedes ponerlo en uno aparte o algo.

2022-06-15 17:52 UTC, JJ commented on OptimizedNeuralNetwork.jl/src/metric_estimation.jl
> -module Metric
Igual, ¿por qué borras esto y han dejado de ser módulos?

2022-06-20 06:18 UTC, BlancaCC commented on OptimizedNeuralNetwork.jl/src/metric_estimation.jl
> -module Metric
Ha pasado todo a un módulo que es la biblioteca, me parecía que tenía más sentido que tener muchos módulo pequeñitos y que se usaban entre ellos.

2022-06-20 06:44 UTC, closed without merging