Aclarar funcionamiento
BlancaCC/TFG-Estudio-de-las-redes-neuronales pull request #120
Opened 2022-06-13 11:58 UTC by BlancaCC

Se pretende con este PR ponerle fin a close #119
Se ha añadido readme y dependencias a toma y manifestaciones

2022-06-14 11:17 UTC, JJ requested changes
Son cambios menores, pero me gustaría que lo aclararas.
También, `make experimentos` sigue sin funcionar con el mismo error.

2022-06-14 11:17 UTC, JJ commented on Project.toml
> +name = "OptimizedNeuralNetwork.jlactiva"
¿`jlactiva`? ¿Se llama así?

2022-06-14 11:17 UTC, JJ commented on Project.toml
> +authors = ["Blanca <blancacano2.71828@gmail.com>"]
¿Esto está bien también?

2022-06-14 11:17 UTC, JJ commented on Readme.md
> +Red neuronal con pesos aleatorio y $n$ neuronas
Lo de arriba puedo entenderlo, pero que borres esto no lo entiendo muy bien. Quien se meta en el repo podrá querer generar la memoria también (o descargarlo)

2022-06-14 11:17 UTC, JJ commented on Readme.md
> +Red neuronal con pesos aleatorio y $n$ neuronas
También: aleatorio*s*

2022-06-14 11:17 UTC, JJ commented on Readme.md
> +RandomWeightsNN(
¿No habrá que importar esto?

2022-06-14 11:17 UTC, JJ commented on Readme.md
> +Creación a partir de matrices
¿Cabecera de algún tipo?

2022-06-14 11:17 UTC, JJ commented on Readme.md
> +FromMatrixNN(S, A, B)
¿Qué es S, A y B?

2022-06-14 11:17 UTC, JJ commented on Readme.md
> +```
Podrías aclarar que algunas son macros... En todo caso, un entorno mejor sería simplemente *items* (y quizás enlaces a la implementación)
Tampoco entiendo muy bien el formato, la verdad, los dos paréntesis y eso.

2022-06-14 11:17 UTC, JJ commented on Readme.md
> +``` Julia
¿Por qué no pones un ejemplo completo?

2022-06-15 09:23 UTC, merged

2022-06-15 09:39 UTC, BlancaCC commented on Readme.md
> +Red neuronal con pesos aleatorio y $n$ neuronas
En la subsección reglas se comenta como general la memoria

2022-06-15 11:56 UTC, BlancaCC commented on Readme.md
> +``` Julia
He enlazado al fichero de ejemplo de uso de la Biblioteca, y lo he comentado y ampliado

2022-06-15 11:58 UTC, BlancaCC commented on Readme.md
> +```
Tienes razón ya lo he concretado mejor

2022-06-15 11:59 UTC, BlancaCC commented on Project.toml
> +authors = ["Blanca <blancacano2.71828@gmail.com>"]
No, ya lo he cambiado