Blanca#39#40  Revisión del capítulo Redes neuronales multicapas son aproximadores universales.
BlancaCC/TFG-Estudio-de-las-redes-neuronales pull request #56
Opened 2022-02-02 14:30 UTC by BlancaCC

Agradecería una revisión del capítulo 3: #40 Redes neuronales multicapas son aproximadores universales.
Esta entrega, aún a medio acabar comprende,  desde la introducción hasta la demostración del lema A.1 (paper en que se basta el capítulo).
Se han eliminado de la entrega las secciones que no desean ser revisadas.
[tfg Día 02-02-2022.pdf](https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/files/7987290/tfg.Dia.02-02-2022.pdf)

2022-02-02 18:43 UTC, JJ requested changes
Aparte de lo que te comento, recuerda siempre poner los fuentes de las imágenes que vayas a incluir.

2022-02-02 18:43 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/introduccion.tex
> +
¿Vas a poner refs solo en los que enlaces o en todos?

2022-02-02 18:43 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/introduccion.tex
> +es pertinente la pregunta de si toda la ingeniería presentada solventa nuestro objetivo principal: Aproximar exitosamente una función genérica desconocida.
¿ingeniería?

2022-02-02 18:43 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/introduccion.tex
> +\begin{teorema}\textbf{Las redes feedfoward multicapa son una clase de aproximadores universales } \label{teo:MFNAUA}
typo: feedfoward. Quizás sería conveniente que miraras #54 antes de seguir escribiendo.

2022-02-02 18:43 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/introduccion.tex
> +    Una red neuronal feedfoward multicapa estándar con tan solo una capa oculta y con una función de activación cualquiera son capaces de aproximar cualquier
error gramatical una... son. Esto es más difícil de pillar automáticamente.

2022-02-02 18:43 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/introduccion.tex
> +En las secciones siguientes, con el fin de una comprensión profunda de las redes neuronales, trataremos de desgranar y profundizar en el artículo y su demostración.
*alcanzar* una comprensión profunda.

2022-02-02 18:43 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/observaciones_dudas_reflexiones.tex
> +¿Qué otras nociones de medir existen? ¿Qué ocurre en estas otras?
Esto quizá debería ser un comentario (pero mejor que comentarios, deberías crear issues relacionados con otros)

2022-02-02 18:43 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/observaciones_dudas_reflexiones.tex
> +¿Se podría establecer una cotar de error al aumentar el número de neuronas?
typo. Also, ver arriba sobre comentarios/issues

2022-02-05 08:29 UTC, BlancaCC commented
Correcciones de Javier: 
[tfg.Dia.02-02-2022Revisado.pdf](https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/files/8007654/tfg.Dia.02-02-2022Revisado.pdf)

2022-02-05 16:21 UTC, BlancaCC commented on doc/capitulos/articulo_rrnn_aproximadores_universales/introduccion.tex
> +
Tenía pensado añadir referencia solo cuando me hiciera falta ¿es conveniente hacer por defecto en todos?

2022-02-06 11:46 UTC, BlancaCC commented on doc/capitulos/articulo_rrnn_aproximadores_universales/observaciones_dudas_reflexiones.tex
> +¿Qué otras nociones de medir existen? ¿Qué ocurre en estas otras?
Toda la razón, eliminaré ese capítulo. Sus elementos pertenecen o a hipótesis de optimización o a dudas.

2022-02-06 18:07 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/introduccion.tex
> +
> Tenía pensado añadir referencia solo cuando me hiciera falta ¿es conveniente hacer por defecto en todos?

En general, si.

2022-02-06 18:11 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/introduccion.tex
> +Aunque las redes neuronales multicapa ya se venían aplicando con anterioridad \cite{4307059},
No incluyas "citas desnudas". Pon "véase", "como afirma x", por parte de... Por otro lado, también trata de usar un estilo donde aparezca el nombre de los autores. APA, por ejemplo. Así dices "por parte de [Foobar, 2011]"

2022-02-06 18:11 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/introduccion.tex
> +y construcción de las redes neuronales
Añade una referencia; en el original la ponía, pero te digo lo mismo que abajo: no incluyas referencias desnudas. Pon "Capítulo \ref{xxx}"

2022-02-06 18:21 UTC, JJ requested changes
Algunas cosas que no están en el PR y que deberían ser generales
* Debes usar cursivas para términos en inglés como *ramp*
* En cada uno de los capítulos, tienes que decir claramente en qué van a avanzar el objetivo/objetivos del TFG y en qué nos acercan a la solución.

Por ejemplo, en este caso decir que el que sean aproximadores universales nos permite usar las redes multicapa para aprender relaciones entre conjuntos de entrada y de salida, y que las condiciones en las que se comportan de esa forma constituyen un espacio de búsqueda. Reducir el espacio de búsqueda nos permitirá conseguir redes neuronales más "baratas"

2022-02-06 18:21 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/introduccion.tex
> + Tal delimitación se propuso en el artículo \cite{HORNIK1989359}
Cita después del título.

2022-02-06 18:21 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/introduccion.tex
> +con éxito una función genérica desconocida.
Normalmente la introducción solo introduce, narrando qué va a haber en el resto de las subsecciones y poniendo enlaces a las mismas.

2022-02-06 18:21 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/introduccion.tex
> +trataremos de desgranar y profundizar en el artículo y su demostración.
Las secciones siguientes incluyen también definiciones, calificadas además como "esenciales". ¿Qué definiciones hay en capítulos anteriores y mencionas al principio?

2022-02-07 07:19 UTC, BlancaCC commented on doc/capitulos/articulo_rrnn_aproximadores_universales/introduccion.tex
> +trataremos de desgranar y profundizar en el artículo y su demostración.
Vale, añadiré un comentario que incluya una comparación con los capítulos anteriores. 
Éstos, aún a medio redactar  (véase rama blanca#43) en esencia lo que hacen es definir conceptos elementales como qué es el aprendizaje, qué componentes tienen y un refinamiento del perceptrón hasta llegar a construir las rrnn y explicar su actualización de pesos. 
Respecto a lo de "esenciales" implemente el título del fichero está mal escogido y lo voy a cambiar en los siguientes commits. En un principio pensé en añadir todas la definiciones en un misma sección. Pero con el fin de que la lectura fuera más amena opté por añadirlas conforme fueran necesarias, mantuve desafortunadamente sin embargo el nombre del fichero que ya ha dejado de ser significativo.

Gracias por las correcciones 😊

2022-03-02 19:20 UTC, JJ approved these changes
OK, adelante, pero habrá que pegarle un último repaso antes de la entrega. No quiero que te bloquees por esto. Por cierto, no pongas los números de issues en el título, sólo añaden ruido y no enlazan a los issues a los que te refieres.

2022-03-02 19:20 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/desgranando_el_articulo/articulo_1_primeras_definiciones.tex
> +Se pretende con las siguientes definiciones una concepción y trabajo preciso de la clase de redes neuronales multicapa feedforward.
¿Esto es definitivo?

2022-03-02 19:20 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/desgranando_el_articulo/articulo_1_primeras_definiciones.tex
> +Se precisa nociones como la de función de activación \ref{def:funcion_activacion_articulo},
*precisan*

2022-03-02 19:20 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/desgranando_el_articulo/articulo_1_primeras_definiciones.tex
> +    otras posibles definiciones menos restrictivas.
¿tales como?...

2022-03-02 19:20 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/desgranando_el_articulo/articulo_1_primeras_definiciones.tex
> +    Para cualquier natural $r$ mayor que cero  denotaremos por $A^r$ al conjunto de todas
¿No se suele usar n para naturales?

2022-03-04 11:09 UTC, closed without merging