Blanca#42 Capítulo de la metodología
BlancaCC/TFG-Estudio-de-las-redes-neuronales pull request #59
Opened 2022-02-05 13:31 UTC by BlancaCC

Capítulo concerniente a la metodología y registro de horas 
El registro de horas #46 no podrá cerrarse hasta dar por terminado el TFG. 
Por lo demás, debería de cerrar los hitos Close #44 #42

Agradecería una revisión previa al mergeo 😊

2022-02-05 14:40 UTC, JJ commented
El close debe ir delante de cada issue que cierre... Y conviene que pongas la causa por la que se cierra (por ejemplo, un enlace al commit)

2022-02-05 14:52 UTC, BlancaCC commented
@JJ Perdón :(  ,
El #42 se cierra ya en los commits, en el último de hecho.
Y el #44 lo cierro ahí porque como indican los commits, forma parte de una sección del capítulo. 

La próxima vez tendré presente que aunque esté en los commits quede también reflejado en el comentario del PR. 

Respecto a cerrar, ¿Existe algún convenio si es mejor en el comentario del PR o en un commits? Me refiero en un caso como este en el que se mergea una rama con el nombre de tal issue

2022-02-05 15:28 UTC, JJ commented
No quería decir eso; se puede cerrar desde el cuerpo del PR o desde el commit; pero *si mencionas en el cuerpo que lo vas a cerrar*, pon el "closes" delante de cada issue y explica por qué o dónde se cierra.

2022-02-05 16:14 UTC, BlancaCC commented
@JJ De acuerdo, entendido para la próxima, gracias

2022-02-07 16:06 UTC, JJ commented
El PR también debe ir en un milestone, como los issues.

2022-02-07 16:29 UTC, JJ requested changes
Creo que tienes que darle una vuelta a los conceptos de personas, historia de usuario y milestone. Una vez más, IV habría resultado relativamente útil aquí. Mira en [este enunciado](http://jj.github.io/IV/documentos/proyecto/1.Infraestructura) las listas de comprobación que tiene que cumplir un milestone, una historia de usuario y demás.

2022-02-07 16:29 UTC, JJ commented on doc/capitulos/metodologia/introduccion.tex
> +    \textcolor{red}{ JJ, el cuarto punto de tu \cite{DBLP:journals/corr/abs-2104-12545} artículo: "Stakeholder collaboration over vertical chains-of-command"
Esto mejor como comentario. También he visto que la gente lo que hace es poner comentarios a su propio PR.
Por otro lado, los stakeholders en este caso somos nosotros, @javiermeri y yo. Quiero pensar que nosotros no te estamos "ordenando" que hagas esto o lo otro, sino que somos los "interesados" en que salga bien el producto y por eso te decimos qué es lo que nos gustaría que tuviera.

2022-02-07 16:29 UTC, JJ commented on doc/capitulos/metodologia/introduccion.tex
> +    enfoque vertical, no por la autoridad; sino por la desigualdad de conocimientos, conduciendo a esa relación "desigual".
Pero en este caso nosotros no somos los "analistas" y tú la "programadora" (como suele suceder el en 99% de los TFGs). Somos personas que podrían beneficiarse del producto (stakeholders) y te decimos qué se puede hacer para que así suceda. No te ordenamos que hagas esta característica o la programes de tal forma.

2022-02-07 16:29 UTC, JJ commented on doc/capitulos/metodologia/introduccion.tex
> +y las respectivas historias de usuario derivadas.
Añade un enlace a dónde lo has desarrollado: apéndice, issue en GitHub, donde sea.

2022-02-07 16:29 UTC, JJ commented on doc/capitulos/metodologia/introduccion.tex
> +\subsection{Personas definidas}
... o a continuación.
En todo caso, "personas" es el resultado de la metodología. La metodología habla de empatizar con el cliente y plasmar en una persona quién es, para poder referirte a él por nombre en las HUs.

2022-02-07 16:29 UTC, JJ commented on doc/capitulos/metodologia/introduccion.tex
> +    \item \textbf{Perfil de usuario Tribunal}
Una "persona" debe tener nombre y apellidos, mira aquí https://www.interaction-design.org/literature/article/personas-why-and-how-you-should-use-them
En este caso, el que sea de informática típicamente, por ejemplo, es la justificación para que en la memoria vayan explicaciones informáticas de los resultados matemáticos.

2022-02-07 16:29 UTC, JJ commented on doc/capitulos/metodologia/introduccion.tex
> +\begin{enumerate}
Esto no creo que haga falta, y menos aquí. Es una descripción para poder justificar las HUs que se apliquen.

2022-02-07 16:29 UTC, JJ commented on doc/capitulos/metodologia/introduccion.tex
> +\item \textbf{Perfil usuario: Benefactor del problema}
Beneficiado, no benefactor. También igual: nombre y apellidos. En este caso creo que es el usuario final, o personas que quieran crear un app o servicios alrededor del producto.

2022-02-07 16:29 UTC, JJ commented on doc/capitulos/metodologia/introduccion.tex
> +\subsection{Historias de usuario}
No sé si debería ser una subsección; tiene bastante importancia. Por otro lado, *deberían* estar en el repo y debes decir en la metdología que esto es lo importante, que se vea claramente cómo se van abordando las HUs desde issues y cómo se van completando en milestones.

2022-02-07 16:29 UTC, JJ commented on doc/capitulos/metodologia/introduccion.tex
> +\subsubsection*{[HU02] Requisitos tribunal}
Como *perteneciente al tribunal* (nombre y apellidos) quiero obtener *estos beneficios* en *este contexto* (leyendo la memoria, o como sea)

2022-02-07 16:29 UTC, JJ commented on doc/capitulos/metodologia/introduccion.tex
> +\subsubsection*{ [HU03] Calidad de la memoria}
la calidad tiene que asegurarse en cada uno de los pasos. No es *nunca* una HU aparte.

2022-02-07 16:29 UTC, JJ commented on doc/capitulos/metodologia/introduccion.tex
> +Los milestones describen productos mínimos viables, nuestro caso hemos definido los siguientes:
Igual, enlazando.

2022-02-18 13:47 UTC, JJ commented
Por favor, recuerda que los PRs se hacen para alcanzar un PMV definido en un milestone. Asigna este (y el resto) al milestone correspondiente (que debería ser el primero, recuerda que no se avanza al milestone siguiente hasta que no se ha terminado el actual)

2022-02-18 13:52 UTC, JJ approved these changes
:+1: 
Arregla el par de cosillas que hay. Luego le daremos otra vuelta más adelante.

2022-02-18 13:52 UTC, JJ commented on .github/workflows/personal-dictionary.txt
> +HUxx
Repetido

2022-02-18 13:52 UTC, JJ commented on doc/capitulos/metodologia/introduccion.tex
> +y la ciencia de datos. Por lo que no es de extrañar que sus beneficios sean extrapolables
", por lo que..." Las oraciones subordinadas no van separadas por punto nunca.

2022-02-18 18:58 UTC, merged