Blanca#40 Revisión del estudio de las redes neuronales
BlancaCC/TFG-Estudio-de-las-redes-neuronales pull request #67
Opened 2022-02-14 11:25 UTC by BlancaCC

Entrego una nueva versión de #40 , la cual agradecería una revisión. 😊
Esta incluye una corrección ortográfica y todas las demandas expuestas en closes #56 por lo que lo cierra. 

Hasta la página 41 se han aplicado los cambios de #56, de ahí en adelante el contenido es novedoso. 

Ante esta nueva versión, destaco lo siguiente: 
1. Ha sido necesario introducir nociones de topología, las he explicado un poco por si para algún lector la materia es desconocida, pero no sé si es suficiente.  
2. Diría que el enunciado del corolario 3.4 (corolario 2.1 en el paper)ha de reformularse diferente a como se indica en el artículo, he escrito en rojo la desigualdad que he intercambiado signo. 
3. También he simplificado la demostración del corolario 3.4 a la dada, así que podría ser que se me haya escapado algún detalle. 

El pdf compilado es el siguiente( se han eliminando secciones no relevantes) : 
[tfg 14 Febrero.pdf](https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/files/8060186/tfg.14.Febrero.pdf)

2022-02-15 09:49 UTC, JavierMeri commented
Mando el .pdf de vuelta revisado. Buen trabajo Blanca
[tfg.14.FebreroRevisado.pdf](https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/files/8067869/tfg.14.FebreroRevisado.pdf)

2022-02-15 10:04 UTC, BlancaCC commented
@JavierMeri Muchísimas gracias Javier 😊
En cuanto pueda incluiré los cambios.

Respecto a los saltos de página a priori no sé quitarlos, ocurren al hacer un include de un .tex 

Los estaba separando para que no hubiera ficheros enormes pero bueno, ya investigaré a ver si existe algún comando o a las muy malas monto algún reprocesado que juntes los .tex a uno al compilar o directamente los copio pego en unos solo una vez que esté toda esa parte redactada y que no vayamos a tocar

2022-02-15 16:39 UTC, JJ requested changes
Dale una vueltecilla todavía, si puede ser. Va muy bien.

2022-02-15 16:39 UTC, JJ commented on .github/workflows/personal-dictionary.txt
> +rrnn
Quizás no deberías aceptarlo en minúscula, aunque supongo que esto será de una etiqueta.

2022-02-15 16:39 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/conclusiones_finales.tex
> +A falta de completar el estudio procedente del teorema \ref{teo:MFNAUA},
¿Esto es un comentario o un texto que va a ir definitivamente?

2022-02-15 16:39 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/conclusiones_finales.tex
> +Consecuencias sobre cuando en \ref{teo:MFNAUA} se estable que el dominio y codominio son finitos.
estable: typo

2022-02-15 16:39 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/desgranando_el_articulo/articulo_1_primeras_definiciones.tex
> +Se pretende con las siguientes definiciones una concepción y trabajo preciso de la clase de redes neuronales multicapa feedforward.
¿"concepción y trabajo preciso" → "establecimiento preciso de la terminología"?

2022-02-15 16:39 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/desgranando_el_articulo/articulo_1_primeras_definiciones.tex
> +Se precisa nociones como la de función de activación \ref{def:funcion_activacion_articulo},
*precisan*

2022-02-15 16:39 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/desgranando_el_articulo/articulo_1_primeras_definiciones.tex
> +    Las funciones de activación son medibles ya que tienen como mucho una cantidad numerable de discontinuidades.
Recuerda poner "para informáticos" #49 las implicaciones de que esto sea así.

2022-02-15 16:39 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/desgranando_el_articulo/articulo_1_primeras_definiciones.tex
> +\end{definicion}
Siempre engancha lo que escribas con el objetivo del proyecto. En este caso, lo importante es cuál de esas funciones sea más "democrática". ¿Todas las funciones van a dar los mismos resultados? ¿Es la más simple válida? Recuerda que *en cada paso* estás avanzando (o no) el objetivo del proyecto, y así tienes que dejarlo claro en la memoria y en la exposición.

2022-02-15 16:39 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/desgranando_el_articulo/articulo_1_primeras_definiciones.tex
> +    Para cualquier función Borel medible $G$, definida de $\R$ a $\R$ y cualquier natural positivo
Antes has hecho referencia a las funciones medibles, pero ninguna referencia a Borel. Igual es lo mismo, pero ni idea.

2022-02-15 16:39 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/desgranando_el_articulo/articulo_1_primeras_definiciones.tex
> +es una combinación lineal de los distintos perceptrones. Con esta misma idea
No, el perceptrón es el conjunto; cada elemento se le llama convencionalmente nodo o neurona. Si no, se hablaría de multicapas de perceptrones, no de perceptrón multicapa.

2022-02-15 16:39 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/desgranando_el_articulo/articulo_1_primeras_definiciones.tex
> +aproximar una función medible a partir de combinaciones lineales de \textit{rectas} evaluadas mediante $G$.
¿Borel medible?

2022-02-15 16:39 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/desgranando_el_articulo/articulo_1_primeras_definiciones.tex
> +    \end{itemize}
Utiliza también la "regla del samurai". Si sacas la espada, tiene que probar sangre.
En este caso, estás mencionando una serie de funciones. Lo suyo sería que alguna, o todas, las compararas en velocidad (y en complejidad). Y que quizás mencionaras aquí que puede haber versiones de las mismas que discreticen el dominio (y que también probarás)

2022-02-15 16:54 UTC, BlancaCC commented on .github/workflows/personal-dictionary.txt
> +rrnn
Cuando marcas la palabra me salen cuatro, entonces no sé bien a cuál te refieres. ¿es perceptrón la que debería estar en mayúscula la primera letra? o rrnn, rrnn es una etiqueta.

2022-02-15 16:55 UTC, BlancaCC commented on Makefile
> +order:
Una pregunta, ¿qué significa nit?

2022-02-16 09:44 UTC, JJ commented on Makefile
> +order:
de "nitpick", un apunte fastidioso o corrección que no afecta realmente la funcionalidad (porque esto es simplemente un nombre de tarea)

2022-02-16 09:45 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/conclusiones_finales.tex
> +A falta de completar el estudio procedente del teorema \ref{teo:MFNAUA},
Entonces es mejor que los pongas en comentarios con %, o usa algún tipo de entorno \textcolor{blue}{} por ejemplo.

2022-02-19 07:16 UTC, BlancaCC commented on doc/capitulos/articulo_rrnn_aproximadores_universales/desgranando_el_articulo/articulo_1_primeras_definiciones.tex
> +    \end{itemize}
Gracias JJ por el comentario, es muy interesante. Me han surgido tres cuestiones al respecto: 
1. Para comparar la velocidad estoy realizando un estudio experimental. ¿Sería de otra forma?
2. ¿A qué te refieres con complejidad? ¿Número de operaciones?
3. En los respectivo a funciones de activación que discreteen el dominio, he buscado cosas como *activation function with discrete boundary* y no he encontrado nada. :( 
Entiendo que puede ser interesante por lo que comente de reducir el espacio utilizando enteros. Lo único que se me ocurre es utilizar funciones como la *ceil* o alguna función propia que sea a trozos *con varios escalones* 
¿A qué tipo de funciones te estás refiriendo?

2022-02-19 07:38 UTC, BlancaCC commented on doc/capitulos/articulo_rrnn_aproximadores_universales/desgranando_el_articulo/articulo_1_primeras_definiciones.tex
> +\end{definicion}
He dejado indicado un comentario que enlace a una sección experimental y que profundice sobre esa cuestión. 
Hasta donde sé, en Deep learning se está optando actualmente por funciones más simples ReLu y no es difícil encontrar artículos que los apoyen,  así que no sé hasta qué punto merece la pena profundizar. 
Dejo algunos artículos que he encontrado:
- Compara rrnn con ReLu frente a otras técnicas de splines: https://arxiv.org/abs/1804.02253 viendo que tiene muy buenos resultado. 
- Compara distintas funciones de activación y comenta que no hay evidencias para decir cuál hay que seleccionar, pero que se avala por ser *mejores* en cuanto a resultado a ReLu y sus variantes: https://www.researchgate.net/publication/344757203_Review_and_Comparison_of_Commonly_Used_Activation_Functions_for_Deep_Neural_Networks
- 
De todas formas, hay algo en común en todos estos estudios: trabajan en redes profundas, la cual no es nuestra situación...

2022-02-19 08:04 UTC, BlancaCC commented on doc/capitulos/articulo_rrnn_aproximadores_universales/desgranando_el_articulo/articulo_1_primeras_definiciones.tex
> +Obsérvese que cada elemento de la sumatoria representa un perceptrón y que la salida final
Está claro que en terminología y topología es como dices un nodo o neurona. Pero a nivel de cálculo cada nodo es un percepción, de ahí el comentario.  De todas formas esto ya lo comento en la sección de construcción de redes neuronales, así que quizás para no liar lo cambiaré.

2022-02-19 08:08 UTC, BlancaCC commented on doc/capitulos/articulo_rrnn_aproximadores_universales/desgranando_el_articulo/articulo_1_primeras_definiciones.tex
> +es una combinación lineal de los distintos perceptrones. Con esta misma idea
De acuerdo, tienes toda la razón, yo llamaba perceptrón a un nodo, lo corrijo, muchas gracias

2022-02-19 08:09 UTC, BlancaCC commented on doc/capitulos/articulo_rrnn_aproximadores_universales/desgranando_el_articulo/articulo_1_primeras_definiciones.tex
> +aproximar una función medible a partir de combinaciones lineales de \textit{rectas} evaluadas mediante $G$.
Voy a dejar esto más claro porque no se entiende, muchas gracias por la observación

2022-02-19 09:11 UTC, JJ approved these changes
Yo creo que ya está listo. Espero haber aclarado todas las dudas.

2022-02-19 09:11 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/conclusiones_finales.tex
>  ¿Se podría intentar analizar si los espacios se puede ampliar?
"se pueden". Por favor, cuidado con la concordancia sujeto-predicado.

2022-02-19 09:11 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/desgranando_el_articulo/articulo_1_primeras_definiciones.tex
> +    \end{itemize}
1. Si. En algunos casos la complejidad algorítmica será suficiente, pero en otros casos no. Para la complejidad algorítmica tendrás que tener en cuenta la implementación, en muchos casos.
2. Si. Una suma no tiene la misma complejidad que un coseno (la misma que una multiplicación, salvo constante).
3. Sí, es muy posible que no haya nada. Por eso es una de las cosas que tienes que (posiblemente) atacar. Pero en general me refiero a las mismas funciones, solo que sobre el dominio de los enteros o racionales.

2022-02-19 09:11 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/desgranando_el_articulo/articulo_1_primeras_definiciones.tex
> +\end{definicion}
El perceptrón multicapa puede tener todas las capas que a uno le dé la gana. No estamos centrándonos en el perceptrón multicapa con retropropagación (aunque también se pueden entrenar redes profundas con retropropagación)

2022-03-02 07:04 UTC, BlancaCC commented
Buenos días, he terminado de redactar todas las demostraciones del artículo, agradecería una revisión @JavierMeri 
[tfg 2 de marzo.pdf](https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/files/8167364/tfg.2.de.marzo.pdf)

2022-03-02 08:05 UTC, JavierMeri commented
Ok Blanca, estoy en ello

2022-03-02 19:13 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/desgranando_el_articulo/articulo_5_colorarios_lp.tex
> +por modelos más simples. ¿Cuántas neuronas \textit{simplificarían} el modelo? Otra solución sería
Terminológicamente, ¿has considerado usar o "reducirían el tamaño del modelo" o "qué número mínimo de neuronas serían necesarios para representar el modelo"? No creo que estemos hablando de la complejidad dle modelo (que podría ser) sólo de su tamaño.

2022-03-02 19:14 UTC, JJ commented on doc/capitulos/articulo_rrnn_aproximadores_universales/conclusiones_finales.tex
>  construcción matemática más abstracta le sería imposible ¿Tienen una aplicación práctica tales definiciones?
¿Has visto estos comentarios?

2022-03-03 12:08 UTC, JavierMeri commented
Buenas, adjunto el .pdf con las correcciones

[tfg.2.de.marzoRevisado.pdf](https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/files/8177618/tfg.2.de.marzoRevisado.pdf)

2022-03-04 11:09 UTC, merged