Blanca#70 Milestones bien definidos
BlancaCC/TFG-Estudio-de-las-redes-neuronales pull request #71
Opened 2022-02-19 16:58 UTC by BlancaCC

Este PR añade una descripción del producto mínimo viable que deben de entregar cada Milestone, 
no solo se refleja en la memoria sino en cada descripción del mismo, resolviendo con ello closes #70 
Además corrige las apariciones de ágil, no como metodología sino como a filosofía, como bien me comentó JJ en  #65

2022-03-02 19:34 UTC, JJ requested changes
Aparte de lo que te comento, enlaza los milestones correspondientes en la web.

2022-03-02 19:34 UTC, JJ commented on doc/capitulos/metodologia/introduccion.tex
> +el trabajo siguiendo un desarrollo ágil, de acorde a las siguientes hipótesis.
"desarrollando con una mentalidad ágil"

2022-03-02 19:34 UTC, JJ commented on doc/capitulos/metodologia/introduccion.tex
> +el trabajo siguiendo un desarrollo ágil, de acorde a las siguientes hipótesis.
: al final.

2022-03-02 19:34 UTC, JJ commented on doc/capitulos/metodologia/introduccion.tex
> +\subsubsection*{[HU01] Optimización redes neuronales.}\label{HU01}
Tienes que formular siempre el problema. No es "encontrara alguna optimización de redes neuronales". El problema es ejecutar el entrenamiento de una red neuronal el hardware más barato o que consuma menos en un tiempo razonable.

2022-03-02 19:34 UTC, JJ commented on doc/capitulos/metodologia/introduccion.tex
> +\subsubsection*{[HU05] Finalizar memoria a tiempo y sin que quede nada pendiente} \label{HUO5}
Esto no puede ser una historia de usuario, forma parte de la viabilidad del producto. Si no se termina a tiempo, el último milestone no sería viable. Recuerda que las historias de usuario son los problemas que quieren resolver.

2022-03-02 19:34 UTC, JJ commented on doc/capitulos/metodologia/introduccion.tex
> +\subsection*{Milestone: Recopilación de bibliografía}
Los milestones están siempre numerados. Y un milestone es siempre un producto mínimamente viable. En el texto lo describes bien, pero en esta descripción hablas de una tarea.

2022-03-02 19:34 UTC, JJ commented on doc/capitulos/metodologia/introduccion.tex
> +\subsection*{Milestone 0: Metodología}
Tiene que ser un producto mínimamente viable.

2022-03-02 19:34 UTC, JJ commented on doc/capitulos/metodologia/introduccion.tex
> +\subsection*{Milestone 1: Estudio de las redes neuronales}
También tiene que ser un PMV...

2022-03-02 19:34 UTC, JJ commented on doc/capitulos/metodologia/introduccion.tex
> +\subsection*{Milestone 2: Hipótesis de optimización}
Tampoco es un PMV.

2022-03-04 16:04 UTC, BlancaCC commented on doc/capitulos/metodologia/introduccion.tex
> +\subsection*{Milestone 1: Estudio de las redes neuronales}
@JJ, lo siento pero termino de entender porqué no es un producto mínimo viable ¿es por cómo está redactado o porque no debiera de aparecer? (voy a explicar cómo lo entiendo hasta ahora para que veamos dónde radica el error): 
1.Entiendo por PVM un entregable que cumpla un mínimo de requisitos (https://es.eserp.com/articulos/producto-minimo-viable/)
2. En el milestone 1, esto refiriendo a que una investigación sobre las redes neuronales resolvería una HU y que su entregable sería una serie de secciones ¿qué es lo que falla aquí?

2022-03-04 16:40 UTC, JJ commented on doc/capitulos/metodologia/introduccion.tex
> +\subsection*{Milestone 1: Estudio de las redes neuronales}
Un PMV es:
1. Un producto. Es algo tangible, un entregable, algo terminado. Puede ser un teorema, código, un capítulo. Pero es un producto. "Estudio" no es un producto. "Un capítulo que describa lo que se sabe de las redes neuronales y que incluya x e y" es un producto.
2. Mínimamente: es lo mínimo exigible para que sea aceptado. No es un estudio exhaustivo, es lo mínimamente necesari para pasar a la siguiente fase. Un "estudio" no es mínimo, salvo que definas claramente cuales son los términos de este estudio.
3. Viable: significa que tienes que decir claramente cuales son los criterios de aceptación dle producto. Ya lo he mencionado antes: serán tests automáticos a diferentes niveles si es código, aprobación por parte de alguien si no... Un estudio, ¿qué criterio de viabilidad tiene? 
Contestando a tu pregunta. La investigación no tiene por qué resolver una HU. Normalmente las HUs no se resuelven más que con el producto final. Los milestones y las HU son ortogonales. y una HU se va moviendo de milestone según se van creando issues que resuelven problemas de complejidad creciente. Por otro lado, una investigación no es un producto. Lo es el resultado de esa investigación, y tiene que estar descrito claramente. En varios sentidos: ver en qué estado deja el producto para emprender el siguiente hito, y unos criterios claros de aceptación que permitan establecer de forma objetiva si se puede (o no) pasar a la etapa siguiente.

2022-03-04 16:41 UTC, JJ commented on doc/capitulos/metodologia/introduccion.tex
> +\subsection*{Milestone 2: Hipótesis de optimización}
En este caso, ¿qué es lo que buscas? ¿Probar una hipótesis? ¿Qué hipótesis? ¿Probar un teorema (mínimo) o lemas adicionales (que no serían mínimos, y que podrían dejarse para el siguiente)?

2022-03-05 09:23 UTC, BlancaCC commented on doc/capitulos/metodologia/introduccion.tex
> +\subsection*{Milestone 1: Estudio de las redes neuronales}
Muchísimas gracias por la aclaración, JJ ♥️

2022-03-05 11:42 UTC, closed without merging

2022-03-05 12:01 UTC, BlancaCC commented
Este PR ha sido cerrado a consecuencia de arreglar #74 , pero ha sido continuado en la rama `milestones`y el PR #75