Funcionamiento redes neuronales
BlancaCC/TFG-Estudio-de-las-redes-neuronales pull request #76
Opened 2022-03-07 18:49 UTC by BlancaCC

Buenas noches @JJ , @JavierMeri, apreciaría si pudierais  revisar el capítulo 2 de introducción a las redes neuronales que está entre las páginas 21 y 28,
en él encontraréis una primera versión de la introducción y construcción de las redes neuronales.

Tened mucho cuidad revisando porque nada está sacado completamente de las referencias que pongo, de hecho no me gustaba completamente la notación ni la demostración y le he metido mucha mano así que puede haber errores.

[tfg-7-marzo.pdf](https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/files/8200092/tfg-7-marzo.pdf)

2022-03-08 13:15 UTC, JJ commented
Blanca, trata de ajustarte a un formato fijo en los cuerpos de los PRs:
1. Describe claramente cual es el *scope*, lo que te vas a limitar a hacer.
2. Menciona los issues que vas a abordar también en el mismo, con el "close" delante si es que cuando se acepte el PR se cierra.

2022-03-08 20:06 UTC, JJ commented on doc/capitulos/introduccion_redes_neuronales/perceptron.tex
> +El perceptrón de Rosenblatt fue presentado en 1962.
cita

2022-03-08 20:06 UTC, JJ commented on doc/capitulos/introduccion_redes_neuronales/perceptron.tex
> +\section{El perceptrón}
Esto no es un elemento, es un tipo de red neuronal.

2022-03-09 06:04 UTC, BlancaCC commented on code/forward-propagation.ipynb
> +{
Cuando explico el algoritmo de forward propagation hay un ejemplo numérico  
<img width="738" alt="Captura de pantalla 2022-03-09 a las 7 02 02" src="https://user-images.githubusercontent.com/32298296/157381839-3b048fc2-fd73-4ccc-ba5d-1f9d0c92c82f.png">
 
y que es calculado en este fichero. Veo la necesidad de poner un ejemplo de este estilo porque compañeros de matemáticas me han comentado que en ocasiones el tribunal ha echado en falta ejemplos. 

¿En qué lugar del directorio lo guardarías?

2022-03-09 06:06 UTC, BlancaCC commented on doc/capitulos/introduccion_redes_neuronales/aprendizaje_introduccion.tex
> +(Información proveniente del capítulo 1 \cite{MostafaLearningFromData})
En los requisitos del TFG de matemáticas había una indicación a comentar las fuentes, ¿cómo se citaría entonces que esa sección proviene de ahí?

2022-03-09 06:09 UTC, BlancaCC commented on doc/capitulos/introduccion_redes_neuronales/aprendizaje_introduccion.tex
> +\subsubsection{Aprendizaje por refuerzo}
El objetivo de añadirlo era ver o explicar si se de podían aplicar ahí también las redes neuronales, es decir, hasta dónde  o qué tipo de problemas intentamos mejorar

2022-03-09 06:13 UTC, JJ commented on doc/capitulos/introduccion_redes_neuronales/aprendizaje_introduccion.tex
> +\subsubsection{Aprendizaje por refuerzo}
Esos objetivos tienen que quedar claros en el texto. Quizás de todos los elementos de los teoremas que se están probando, algunos sean extensibles a otros modelos. Tendrás que aclarar cuales, pero donde los menciones.

2022-03-09 06:15 UTC, BlancaCC commented on doc/capitulos/introduccion_redes_neuronales/perceptron.tex
> +El perceptrón de Rosenblatt fue presentado en 1962.
El fichero perceptrón al final no aparece en el entregable de PMV (no se incluye en el tfg.tex) perdón por no borrarlo y hacerte corregir cosas de más.

 A priori comencé a investigarlo (y por ello está ese fichero a modo de notas) porque al compartir la estructura de os nodos de una red Neural pensé que podría aportarnos algo, finalmente lo descarté porque el *método de aprender* no tiene nada que ver con el utilizado con las redes neuronales.

2022-03-09 07:57 UTC, BlancaCC commented on doc/capitulos/introduccion_redes_neuronales/aprendizaje_introduccion.tex
> +Las redes neuronales son partícipes en los tres tipos de aprendizaje
Tienes toda la razón, al final lo que he hecho es imitar cómo se cuenta en este paper https://doi.org/10.1007/s42979-021-00592-x donde la jerarquía es 

<img width="738" alt="Captura de pantalla 2022-03-09 a las 8 54 51" src="https://user-images.githubusercontent.com/32298296/157397451-8cb1ce17-a53d-4b2c-98b6-db63ac9d6048.png">

2022-03-09 11:36 UTC, JJ commented on code/forward-propagation.ipynb
> +{
Como todas las decisiones, las tienes que tomar tú, Blanca. No estoy discutiendo la necesidad de poner un ejemplo o no, sino simplemente que todos los ficheros deben estar en el directorio que dicten los issues que resuelvan y las buenas prácticas.

2022-03-09 11:42 UTC, JJ commented on doc/capitulos/introduccion_redes_neuronales/aprendizaje_introduccion.tex
> +(Información proveniente del capítulo 1 \cite{MostafaLearningFromData})
Las citas tienen que seguir un formato específico, y el texto tiene que ser narrativo. Si está copiada directamente, tienes que usar el entorno correspondiente. Si está inspirada o reescrita, tendrás que narrarlo dentro de la estructura dle capítulo.

2022-03-09 11:42 UTC, JJ commented on doc/capitulos/introduccion_redes_neuronales/aprendizaje_introduccion.tex
> +\subsubsection{Aprendizaje por refuerzo}
NO me lo cuentes a mi, cuéntalo en el texto.

2022-03-09 11:44 UTC, JJ commented on code/forward-propagation.ipynb
> +{
Ten en cuenta también el concepto de "scope" de un PR, que lo que dice es principalmente que hay que tener muy claro qué es lo que se pretende con dicho PR y no meter todo lo que aparezca por el camino. Si necesitas los ejemplos para algún fin, tiene como siempre que seguir una HU y abrirse el issue correspondiente.

2022-03-09 11:50 UTC, JJ requested changes
Casi que los Jupyter notebooks deberían ir a su propio PR, en vez de estar en este. Es la primera introducción de código, y no está claro que tengan que ir en el directorio en el que están.

2022-03-09 11:50 UTC, JJ commented on code/perceptrón.ipynb
> +       "GradienteDescendente (generic function with 1 method)"
"Descendiente"
Cualquier código también tiene que testearse, y sería mejor que lo pusieras en un PR aparte. En este caso, ni siiquiera se podía ver en la versión por omisión porque era demasiado grande.

2022-03-09 11:50 UTC, JJ commented on code/perceptrón.ipynb
> +    "function Imprime(w)\n",
El problema con este código es que es muy difícil de revisar; pero si vas a usar cualquier código común, funciones y demás, deberías ponerlo en una biblioteca aparte y por supuesto testearlo.
También tendrías que meter en el fichero de tareas una para instalar y lanzar el Jupyter notebook con Julia. Y todo eso, por supuesto que mucho mejor en un PR aparte, que tenga solo esa función.

2022-03-09 19:03 UTC, BlancaCC commented on doc/capitulos/introduccion_redes_neuronales/aprendizaje_introduccion.tex
> +\subsubsection{Aprendizaje por refuerzo}
Ya está hecho en el commit https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/pull/76/commits/3eaf4cfa2d8b58aa20ad1c53ee1dcf07c7b35fed

2022-03-09 19:05 UTC, BlancaCC commented on doc/capitulos/introduccion_redes_neuronales/aprendizaje_introduccion.tex
> +(Información proveniente del capítulo 1 \cite{MostafaLearningFromData})
Ya está arreglado en el commit https://github.com/BlancaCC/TFG-Estudio-de-las-redes-neuronales/pull/76/commits/3eaf4cfa2d8b58aa20ad1c53ee1dcf07c7b35fed

2022-03-09 19:12 UTC, BlancaCC commented on code/perceptrón.ipynb
> +       "GradienteDescendente (generic function with 1 method)"
De acuerdo, de todas formas este Jupyter lo he borrado porque no forma parte del PMV

2022-03-09 19:15 UTC, JJ commented on code/perceptrón.ipynb
> +       "GradienteDescendente (generic function with 1 method)"
¡No borres nada! Simplemente pásalo a otra rama...

2022-03-09 19:31 UTC, BlancaCC commented on code/forward-propagation.ipynb
> +{
Gracias por inculcarme las buenas prácticas me acabo de dar cuenta que no estaba entendiendo bien la estructura del repo, el problema era que no visualizaba el directorio entero como un todo, si no que por una parte estaba el código y por otra la memoria. 
Ahora he añadido cada respectivo notebook con el subdirectorio de acorde a su temática. 

También tienes razón con atomizar más los PR y también con que debiera de haber exteriorizado lo de los ejemplos, añado la historia de usuario y lo de los PR lo aplico de ahora en adelante.

2022-03-13 13:28 UTC, merged