Comparativas funciones activación
BlancaCC/TFG-Estudio-de-las-redes-neuronales pull request #96
Opened 2022-05-18 10:00 UTC by BlancaCC

Este PR contiene el código que realiza las comparativas de las funciones de activación. 

Agradecería a @JJ que lo revisara por dos motivos: 
- No me gustan ni un pelo los resultado, debe de haber algo mal en la medición que no sé qué es, pero no veo normal que las desviaciones típicas de funciones constantes salgan tan grandes y que las que teóricamente iban a ser peores no lo sean.
- Por si conoce de mejores técnicas, metodologías y organización que me pudiera orientar.

2022-05-18 10:08 UTC, BlancaCC commented
Dejo aquí ejemplos de ejecuciones del código, para que podáis ver los resultados actuales
: 
<img width="1113" alt="Captura de Pantalla 2022-05-18 a las 12 07 57" src="https://user-images.githubusercontent.com/32298296/169014935-b37ec650-7d4b-4019-8dce-554e5b9756a6.png">

2022-05-19 18:04 UTC, JJ commented
Los dos issues a los que te refieres son esencialmente el mismo; en el primero formulas el problema, que es el que tiene que tener el issue. El #80 podías convertirlo en una medida experimental para la historia de usuario del tribunal #49

2022-05-19 18:05 UTC, JJ commented
> Dejo aquí ejemplos de ejecuciones del código, para que podáis ver los resultados actuales : <img alt="Captura de Pantalla 2022-05-18 a las 12 07 57" width="1113" src="https://user-images.githubusercontent.com/32298296/169014935-b37ec650-7d4b-4019-8dce-554e5b9756a6.png">

Si quieres hacer una comparación, lo tienes que hacer con la mediana y compararlas con el test de Wilcoxon. Si eso te parece excesivo, simplemente poner un boxplot de los resultados; poner cada resultado individual no aporta mucha información.

2022-05-19 18:06 UTC, JJ commented
Además, deberías hacer al menos 12-15 mediciones.

2022-05-19 18:07 UTC, JJ commented
Estos experimentos tienen que ser también repetibles y por tanto tienes que iniciar un fichero de tareas, Makefile o el que veas más adecuado para Julia. La elección de este sistema tienes también que justificarlo como parte de la metodología.

2022-05-19 18:47 UTC, JJ requested changes
Creo que tendrás que darle una vuelta o dos más. Lo principal es que sigas la metodología a rajatabla. Este PR es también el primero con algo de código, por eso es importante que lo hagas bien.

2022-05-19 18:47 UTC, JJ commented on .github/workflows/neural-networks-library.yaml
> +        - run: make test-library
OK, veo que al menos esto sí lo tienes en el Makefile. Lo habitual, sin embargo, es simplemente `make test`

2022-05-19 18:47 UTC, JJ commented on Biblioteca-Redes-Neuronales/src/activation_functions.jl
> +Return a Threshold Function defined by `polinamial`and `t`.
typo: polynomial

2022-05-19 18:47 UTC, JJ commented on Biblioteca-Redes-Neuronales/src/activation_functions.jl
> +function CreateThreshold(polinomial, t::Real)
typo: polynomial

2022-05-19 18:47 UTC, JJ commented on Biblioteca-Redes-Neuronales/src/activation_functions.jl
> +module ActivationFunctions
Hay un solo mensaje de commit en este fichero. Se refiere a un issue en el que no hay aparentemente ninguna relación con, al menos, las primeras funciones. Para diseñar una clase tienes que seguir un proceso de domain driven design, recuerda que lo hablamos al principio. Es una metodología de diseño más o menos tan precisa como las matemáticas. Y lo que dice esa metodología es que la modularización debe seguir un proceso que va del dominio del problema  a la programación.
Esto no quiere decir que en este caso específico no esté bien; es bastante razonable que haya funciones de activación. Pero *no tienes ningún issue que diga qué es lo que son, y qué es lo que hacen, qué restricciones tienen, ni qué problema resuelven*. Tampoco la HU a la que esto está asignado, #65, ni el milestone, el 1, parece que encajen demasiado bien.
En resumen: el código en sí no se puede afirmar si está bien o mal hasta que sabes en base a qué lo has desarrollado, y eso no lo has hecho en este caso.

2022-05-19 18:47 UTC, JJ commented on Biblioteca-Redes-Neuronales/src/activation_functions.jl
> +export CreateThreshold
¿Esta es la mejor práctica en Julia?
En la memoria tienes que dejar claro que se siguen las mejores prácticas en el lenguaje de programación que vayas a usar; por cierto, también tiene sque justificar en la memoria el uso de este lenguaje de programación, antes de escribir las primeras líneas.

2022-05-19 18:47 UTC, JJ commented on Biblioteca-Redes-Neuronales/test/activation_functions.test.jl
> +#  treshold a partir del polinomio p
typo

2022-05-19 18:47 UTC, JJ commented on Biblioteca-Redes-Neuronales/test/activation_functions.test.jl
> +@testset "Activations functions" begin
Si no se guían los tests por los casos de uso (que no tienes en el caso de estas funciones) realmente no estás haciendo nada. Los tests tienen que probar el comportamiento en los casos reales en los que se vaya a usar.

2022-05-19 18:47 UTC, JJ commented on Biblioteca-Redes-Neuronales/test/activation_functions.test.jl
> +    @test ReLU(2) >1
Si has probado matemáticamente que las funciones tienen que cumplir unas condiciones, *aquí* es donde tienes que probarlo. ¿Estas funciones son... "medibles" era? ¿Cuál es el rango de entrada y salida?

2022-05-19 18:47 UTC, JJ commented on Biblioteca-Redes-Neuronales/test/one_layer_neural_network.test.jl
> +end
Igualmente, tienes que comprobar comportamiento, no atributos. Un simple test de aleatoriedad podría servir (un peso no es igual al siguiente, o algo así)

2022-05-19 18:47 UTC, JJ commented on Biblioteca-Redes-Neuronales/test/one_layer_neural_network.test.jl
> +using .ModuleOneLayerNeuralNetwork
¿Por qué está "Module" en el nombre?

2022-05-22 16:23 UTC, JJ requested changes
Nada especialmente grave, pero pequeñas cosas a las que habría que darle una vuelta.

2022-05-22 16:23 UTC, JJ commented on Experimentos/comparativas-funciones-activacion/velocidad_funciones_activacion.jl
> +DIRECTORIO_RESULTADOS = "Experimentos/comparativas-funciones-activacion/"
En todo lo que es gestión experimenal, deberías usar un fichero de configuración en vez de hardcodearlos. Os he puesto en el grupo de Telegram como hacer este tipo de cosas.

2022-05-22 16:23 UTC, JJ commented on Makefile
> +test: spell test-library
Según vayas añadiendo código y tests de verdad, igual deberías cambiar esto de nombre.

2022-05-22 16:23 UTC, JJ commented on Memoria/capitulos/5-Estudio_experimental/funciones_activacion.tex
> +que procederemos a realizar un análisis del costo de las redes neuronales.
Caracteriza el contexto; es decir, voy a trabajar sobre *x* funciones de activación con estas características.

2022-05-22 16:23 UTC, JJ commented on Biblioteca-Redes-Neuronales/src/one_layer_neuronal_network.jl
> +    ∑= map(h.activation_function,s)
Mola uso de letras griegas

2022-05-22 16:23 UTC, JJ commented on Memoria/capitulos/5-Estudio_experimental/funciones_activacion.tex
> +menos infinito.
Algunas funciones no cumplen esto. ¿Seguro que esta es la definición normal? ¿No será que estén acotadas dentro de dominio de las entradas que tengan?

2022-05-22 16:23 UTC, JJ commented on Memoria/capitulos/5-Estudio_experimental/funciones_activacion.tex
> +además también incluiremos la función de activación identidad.
Que tampoco tiene límite. Pero esto debería referirse a otra parte de la memoria, no a las citas. ¿Qué significa que sea no polinómica?

2022-05-22 16:23 UTC, JJ commented on Memoria/capitulos/5-Estudio_experimental/funciones_activacion.tex
> +    igual al espacio de redes neuronales creado con la función de activación $\gamma$.
¿Cómo defines igualdad entre espacios?

2022-05-22 18:41 UTC, BlancaCC commented on Biblioteca-Redes-Neuronales/src/activation_functions.jl
> +    if(x<0)
Agradezco muchísimos estos comentarios porque no tengo ni idea de este tipo de mejoras en Julia. Me las apunto, las investigo y las aplicaré, cualquier otra cosa al respecto escríbeme por favor. 🥰

2022-05-23 05:08 UTC, BlancaCC commented on Experimentos/comparativas-funciones-activacion/velocidad_funciones_activacion.jl
> +DIRECTORIO_RESULTADOS = "Experimentos/comparativas-funciones-activacion/"
JJ, no sé bien a qué te refieres. En ese párrafo explico que durante las demostraciones teóricas hemos usado una definición más estricta de función de activación, que no es la normal  y que ahora la vamos a relajar.

2022-05-23 05:23 UTC, BlancaCC commented on Makefile
> +test: spell test-library
Que no sea un polinomio. Añadiré referencias a la sección de definición de las funciones de activación, comentaré allí estas cosas con más claridad así como el concepto de polinómica, gracias

2022-05-23 05:30 UTC, BlancaCC commented on Memoria/capitulos/5-Estudio_experimental/funciones_activacion.tex
> +que procederemos a realizar un análisis del costo de las redes neuronales.
Añadiré nota aclaratoria, dos espacios son iguales cuando como  entendidos como conjunto tienen los mismo elementos.

2022-05-23 05:33 UTC, BlancaCC commented on Experimentos/comparativas-funciones-activacion/visualizacion-funciones-activacion.jl
>  function MuestraYGuarda(fa :: FuncionActivacion, img_path:: String)
Remito este issue a #99

2022-05-23 05:41 UTC, BlancaCC commented on Biblioteca-Redes-Neuronales/src/activation_functions.jl
> +    if(x<0)
He transladado este comentario al #98

2022-05-23 05:43 UTC, BlancaCC commented on Experimentos/comparativas-funciones-activacion/visualizacion-funciones-activacion.jl
> +    FuncionActivacion("Sigmoid", Sigmoid, -4,4),
Lo necesitaba para #99 la idea es la siguiente: 
-  Si son parecidas, aproximarás más o menos igual y por lo tanto merece la pena ver cuál nos renta más. 
- La visualización de las funciones es una forma intuitiva y rápida de justificar la similitud

2022-05-23 17:20 UTC, BlancaCC commented
@JJ , De ser aprobado el commit anterior en lo que respecta a los issue #98 y #100 debería de cerrarlos.

2022-05-23 17:27 UTC, JJ commented on Experimentos/comparativas-funciones-activacion/velocidad_funciones_activacion.jl
> +DIRECTORIO_RESULTADOS = "Experimentos/comparativas-funciones-activacion/"
Simplemente, que leas esos valores de directorio de resultados y esas cosas de un fichero de configuración.

2022-05-23 17:32 UTC, BlancaCC commented
@JJ No, no he puesto closes, lo decía por hacerte un llamamiento de atención y dejar constancia de que habría que cerrarlos dado el caso. Gracias JJ

2022-05-24 15:23 UTC, JJ commented
Ahora parece que tiene un error de test; cuando corrijas eso y los otros comentarios me dices.

2022-05-25 15:10 UTC, BlancaCC commented on Biblioteca-Redes-Neuronales/test/one_layer_neural_network.test.jl
> +end
Sinceramente este parte de código no encaja con este PR, debiera de haber sido fruto de un DDD que hubiera salido de #107 (ya que allí sí será necesario implementar redes neuronales y aquí todavía no...) 

Voy a dejar sin resolver por ahora esto para hacerlo de manera más organizada llegado el momento conveniente.

2022-05-25 15:22 UTC, BlancaCC commented on Biblioteca-Redes-Neuronales/test/one_layer_neural_network.test.jl
> +using .ModuleOneLayerNeuralNetwork
Se aplica lo mismo que en el comentario anterior, debería de pertenecer a #107 
Perdón por el caos :(

2022-05-25 17:00 UTC, JJ requested changes
Ya sé que he pedido cambios, pero aqui alguno más. Y también es conveniente que mires una serie de cosas para las funciones de evaluación. Aunque en general en la carrera parece que no han enseñado otra cosa que aplicar la sintaxis, hay muchas cosas que tienes que tener en cuenta a la hora de diseñar un conjunto de objetos que sigan un interfaz  común, como el caso d estas funciones. Vamos a ver una serie de conceptos.

## Functor

Un functor en general (no en Haskell y lenguajes funcionales puros) son objetos que tienen sintaxis de funciones, es decir, a los que puedes llamar de la forma `functor( arg1, arg2...)`. En general, si quieres que varias funciones sigan un mismo interfaz, tienes que definir una clase base abstracta que defina ese interfaz (es decir, una clase base que no se puede implementar) y clases derivadas que implementen la lógica de negocio. Por el principio de sustitución de Liskov, puedes usar cualquier clase derivada donde podrías usar la base.

### Conclusión

Mira el concepto de functor y aplícalo a este caso determinado. Si simplemetne usas funciones diferentes, el interfaz para sustituir una clase por otra va a ser complejo y además poco escalable.

## Tipos restringidos

Julia tiene un [sistema de tipos](https://docs.julialang.org/en/v1/manual/types/) bastante rico, incluyendo tipos paramétricos  mediante lo que le llama [constructores interiores](https://docs.julialang.org/en/v1/manual/constructors/#Inner-Constructor-Methods-1) Es decir, puedes por ejemplo creat un tipo de real que sólo tome valores entre -1 y 1, o reales negativos o lo que sea.

### Conclusión

Como dicen [aquí](https://stackoverflow.com/a/31904634/891440), "hay un tipo para ello". En Julia, definir tipos siempre permite tener resultados interesantes.

## *Dispatch* múltiple

Muchos lenguajes permiten definir varias versiones de métodos, cada una con tipos diferentes. A las diferentes versiones de la función se le llama ["métodos" en Julia](https://docs.julialang.org/en/v1/manual/methods/) Por ejemplo, puedes definir una versión de la función para números que estén entre -1 y 1 (para lo que tendrás un tipo) y otra versión para cualquier otro número.

> En realidad este es un ejemplo no muy bueno, la verdad. Idealmente, el dispatch múltiple debería poder hacerse con los *valores* de los parámetros de una función, no sólo con los tipos. Raku lo permite, por ejemplo, Julia no. Si miras la respuesta a SO anterior, simplemente dice que no puede hacerse.

### Conclusión

Si tienes funciones donde te encuentras haciendo muchos if para ver el valor que tiene un argumento, convertir diferentes rangos de valores de un argumento en tipos (si es una operación rápida y sólo hay dos tipos, esencialmente si no tienes que hacer el mismo `if` que harías dentro de la función) puede ser una forma *type-safe* de hacer lo mismo.

## Mega-conclusión

Trata de buscar siempre las estructuras del lenguaje más adecuadas para cada tema determinado. En este caso functores :heavy_check_mark: tipos restringidos/multiple dispatch :-1: pero en todo caso conocer todos los mecanismos del lenguaje de programación es positivo (y muestra iniciativa y autonomía para #49 )

2022-05-25 19:06 UTC, BlancaCC commented on .github/workflows/neural-networks-library.yaml
> +    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
Iba a sacarlo en una rama para que vieras los cambios pero he hecho el push sin olvidándome de sacar otra rama, pero bueno, ya está solucionado y close #104

2022-06-02 12:58 UTC, merged